In [1]:
import sys
import pandas as pd
import json
import os
import matplotlib.pyplot as plt
from jiwer import RemovePunctuation
from dotenv import load_dotenv
import spacy
from tqdm import tqdm


!{sys.executable} -m pip install chat_gpt_asr
from chat_gpt_asr.alignment import *

# read env variables
load_dotenv()
Root = os.getenv("ROOT_PATH")

# load spacy
nlp = spacy.load("en_core_web_sm")

Requirement already satisfied: chat_gpt_asr in /home/mnaderi/miniconda3/lib/python3.10/site-packages (0.1.0)

## Read dataset

In [5]:
# read dataset
path = os.path.join(Root, "results/results-dev-set/results_noisy/results_tiny/results_sentence_confidence_tiny/results_GPT-3.5-Turbo_tiny/gpt-3.5-turbo-0125/results_without_sentence_confidence_tiny/corrected_transcriptions_sentence_confidence_tiny.json")

#path = "/home/mnaderi/Documents/thesis/chat-gpt-asr/results/results-dev-set/results_noisy/results_tiny/results_sentence_confidence_tiny/results_GPT-3.5-Turbo_tiny/gpt-3.5-turbo-0125/results_without_sentence_confidence_tiny/corrected_transcriptions_sentence_confidence_tiny.json"

with open(path, "r") as f:
    data = json.load(f)
    
    transcriptions = [RemovePunctuation()(d["asr_transcription"]["text"]).lower().strip() for d in data]
    reference_transcriptions = [RemovePunctuation()(d["reference_transcription"]).lower().strip() for d in data]
    corrected_transcriptions = [RemovePunctuation()(d["corrected_asr_transcription"]).lower().strip() for d in data]

## Parts of speech

In [6]:

def identify_operation(a, l):
    if a != "" and l == "":
        return "D"
    elif a == "" and l != "":
        return "I"
    elif a != "" and l != "" and a != l:
        return "S"
    else:
        return '-'

def identify_edit_type_1(rr, aa, ll):
    edit_types = []
    operations = []
    edits = {"Improved":[],"IntroducedError":[],"LeftCorrect":[],"LeftIncorrect":[]}
    # rr, aa, ll = align3(ref, asr, llm, tokenizer_fn)
    if len(rr) == len(aa) == len(ll):
        for r,a,l in zip(rr,aa,ll):
            operation = identify_operation(a, l)
            operations.append(operation)
            if a == l == r:
                edit_types.append("LeftCorrect")  # left it correct
                edits["LeftCorrect"].append((a,l,r))
            elif a != l and l == r:
                edit_types.append("Improved")  # improve it
                edits["Improved"].append((a,l,r))
            elif a != r and l != r:
                edit_types.append("LeftIncorrect")  # left it incorrect
                edits["LeftIncorrect"].append((a,l,r))
            elif a == r and l != r:
                edit_types.append("IntroducedError")  # introducing an error
                edits["IntroducedError"].append((a,l,r))
    else:
        raise Exception
    return edit_types, edits, operations

def preprocess(ref, asr, llm, tokenizer_fn):

    # list of tokens of aligned ref, asr, and llm 
    ref_aligned, asr_aligned, llm_aligned = align3(ref,asr,llm, tokenizer_fn=tokenizer_fn)

    # identify the edit_types and operations
    edit_types, edits, operations = identify_edit_type_1(ref_aligned, asr_aligned, llm_aligned)
    llm_aligned_str = " ".join([r if r else "*" for r in llm_aligned])
    asr_aligned_str = " ".join([r if r else "*" for r in asr_aligned])
    ref_aligned_str = " ".join([r if r else "*" for r in ref_aligned])
    
    # string of aligned ref, asr, and llm with '' replaced by *
    llm_doc = nlp(llm_aligned_str)
    ref_doc = nlp(ref_aligned_str)
    asr_doc = nlp(asr_aligned_str)
    assert len(llm_doc) == len(asr_doc) == len(ref_doc)

    d = {}
    for i in range(len(asr_doc)):

        operation = operations[i]
        edit_type = edit_types[i]
        a_token = asr_doc[i]
        a_pos = "MASKED" if a_token.text == "*" else a_token.pos_
        
        l_token = llm_doc[i]
        l_pos = "MASKED" if l_token.text == "*" else l_token.pos_

        # identify pos
        if operation == 'I':
            pos = l_pos
        elif operation == 'D':
            pos = a_pos
        elif operation == '-':
            pos = a_pos
        elif operation == 'S':
            pos = a_pos
    
        d[(edit_type, pos)] = d.get((edit_type, pos), 0) + 1
        # print(f"{operation=}, {edit_type=}, {a_pos=} {l_pos=}, {pos=}")

    return d

def tokenizer_fn(s):
    return [token.text for token in nlp(s)]

In [10]:
import multiprocessing as mp

# parallelized approach
def process_triplet(input):
    asr, ref, llm = input
    # process_id = os.getpid()
    # print(f"Process ID: {process_id}, Index: {index}")
    return preprocess(ref, asr, llm, tokenizer_fn)

num_processes = mp.cpu_count()  
with mp.Pool(processes=num_processes) as pool:
    # Map function to distribute tasks across processes
    results = list(
        pool.map(
            process_triplet, 
            zip(transcriptions, reference_transcriptions, corrected_transcriptions)
        )
    )


results

[{('LeftCorrect', 'VERB'): 4,
  ('LeftCorrect', 'ADP'): 4,
  ('LeftCorrect', 'PRON'): 4,
  ('LeftCorrect', 'DET'): 2,
  ('LeftCorrect', 'NOUN'): 3,
  ('LeftCorrect', 'ADJ'): 3,
  ('LeftCorrect', 'CCONJ'): 1,
  ('Improved', 'NOUN'): 1},
 {('LeftCorrect', 'PRON'): 1,
  ('LeftCorrect', 'VERB'): 1,
  ('LeftCorrect', 'ADP'): 2,
  ('LeftCorrect', 'DET'): 2,
  ('LeftCorrect', 'NOUN'): 3,
  ('Improved', 'ADV'): 1},
 {('LeftCorrect', 'ADP'): 2,
  ('LeftCorrect', 'NOUN'): 2,
  ('LeftCorrect', 'PRON'): 3,
  ('LeftCorrect', 'AUX'): 1,
  ('LeftCorrect', 'VERB'): 2,
  ('LeftCorrect', 'ADV'): 2,
  ('LeftCorrect', 'ADJ'): 1},
 {('LeftCorrect', 'PRON'): 9,
  ('LeftCorrect', 'AUX'): 3,
  ('LeftCorrect', 'VERB'): 5,
  ('LeftCorrect', 'DET'): 1,
  ('LeftCorrect', 'NOUN'): 4,
  ('LeftCorrect', 'CCONJ'): 1,
  ('Improved', 'PRON'): 1,
  ('LeftCorrect', 'ADP'): 1,
  ('LeftCorrect', 'ADV'): 1,
  ('Improved', 'VERB'): 1},
 {('LeftCorrect', 'INTJ'): 1,
  ('LeftIncorrect', 'MASKED'): 1,
  ('LeftCorrect', 'VERB'): 2,
  ('LeftCorrect', 'PRON'): 2,
  ('LeftCorrect', 'DET'): 2,
  ('LeftCorrect', 'NOUN'): 2,
  ('LeftCorrect', 'AUX'): 1},
 {('LeftCorrect', 'PRON'): 1,
  ('LeftIncorrect', 'VERB'): 1,
  ('LeftIncorrect', 'PROPN'): 1,
  ('IntroducedError', 'SCONJ'): 2,
  ('LeftIncorrect', 'PRON'): 1,
  ('LeftCorrect', 'AUX'): 1,
  ('LeftCorrect', 'PART'): 1,
  ('LeftCorrect', 'VERB'): 1},
 {('LeftCorrect', 'DET'): 1,
  ('LeftIncorrect', 'NOUN'): 1,
  ('LeftCorrect', 'PRON'): 1,
  ('LeftCorrect', 'AUX'): 1,
  ('LeftCorrect', 'VERB'): 1,
  ('LeftCorrect', 'ADP'): 1,
  ('LeftCorrect', 'NOUN'): 1},
 {('LeftCorrect', 'SCONJ'): 1,
  ('LeftCorrect', 'PRON'): 4,
  ('LeftCorrect', 'VERB'): 4,
  ('LeftCorrect', 'DET'): 3,
  ('LeftCorrect', 'NOUN'): 8,
  ('LeftCorrect', 'CCONJ'): 1,
  ('LeftCorrect', 'ADJ'): 1,
  ('LeftCorrect', 'ADV'): 1,
  ('Improved', 'DET'): 1,
  ('Improved', 'NOUN'): 2,
  ('LeftCorrect', 'ADP'): 3,
  ('LeftIncorrect', 'MASKED'): 1,
  ('LeftIncorrect', 'VERB'): 2,
  ('LeftIncorrect', 'CCONJ'): 1,
  ('LeftIncorrect', 'ADP'): 1},
 {('LeftCorrect', 'INTJ'): 1,
  ('LeftCorrect', 'PRON'): 1,
  ('LeftCorrect', 'VERB'): 1,
  ('LeftCorrect', 'ADP'): 1,
  ('LeftCorrect', 'DET'): 1,
  ('LeftCorrect', 'ADJ'): 1,
  ('LeftCorrect', 'NOUN'): 1},
 {('LeftCorrect', 'CCONJ'): 1,
  ('LeftCorrect', 'DET'): 1,
  ('LeftCorrect', 'NOUN'): 4,
  ('LeftIncorrect', 'VERB'): 1,
  ('LeftCorrect', 'PRON'): 4,
  ('LeftCorrect', 'VERB'): 1,
  ('LeftIncorrect', 'NOUN'): 1,
  ('Improved', 'ADP'): 1},
 {('LeftCorrect', 'PRON'): 4,
  ('LeftCorrect', 'VERB'): 2,
  ('LeftCorrect', 'ADV'): 1,
  ('LeftCorrect', 'NUM'): 1,
  ('LeftCorrect', 'NOUN'): 2,
  ('LeftCorrect', 'AUX'): 1},
 {('LeftCorrect', 'PRON'): 4,
  ('LeftCorrect', 'VERB'): 2,
  ('LeftCorrect', 'ADP'): 1,
  ('LeftCorrect', 'NOUN'): 1,
  ('LeftCorrect', 'AUX'): 3,
  ('LeftCorrect', 'PART'): 1,
  ('LeftCorrect', 'ADJ'): 1},
 {('LeftCorrect', 'PRON'): 3,
  ('LeftCorrect', 'VERB'): 2,
  ('LeftCorrect', 'PROPN'): 1,
  ('LeftCorrect', 'DET'): 4,
  ('LeftIncorrect', 'NOUN'): 1,
  ('LeftCorrect', 'ADP'): 1,
  ('LeftCorrect', 'NOUN'): 2,
  ('LeftCorrect', 'ADJ'): 4,
  ('LeftCorrect', 'INTJ'): 1,
  ('LeftCorrect', 'AUX'): 1},
 {('LeftCorrect', 'PRON'): 1,
  ('LeftCorrect', 'AUX'): 1,
  ('LeftCorrect', 'DET'): 2,
  ('LeftCorrect', 'NOUN'): 2,
  ('LeftCorrect', 'ADV'): 1,
  ('LeftCorrect', 'CCONJ'): 1,
  ('LeftCorrect', 'PART'): 1},
 {('LeftCorrect', 'VERB'): 1, ('IntroducedError', 'PRON'): 1},
 {('LeftCorrect', 'PRON'): 3,
  ('LeftIncorrect', 'VERB'): 1,
  ('LeftIncorrect', 'PRON'): 1,
  ('LeftIncorrect', 'AUX'): 1,
  ('LeftCorrect', 'NOUN'): 1},
 {('LeftCorrect', 'AUX'): 1,
  ('LeftCorrect', 'PRON'): 1,
  ('LeftCorrect', 'VERB'): 1,
  ('LeftCorrect', 'NOUN'): 1},
 {('LeftCorrect', 'PRON'): 2,
  ('LeftCorrect', 'VERB'): 3,
  ('LeftCorrect', 'ADP'): 1,
  ('LeftCorrect', 'DET'): 1,
  ('LeftCorrect', 'NOUN'): 1},
 {('LeftCorrect', 'VERB'): 2,
  ('LeftCorrect', 'PROPN'): 1,
  ('LeftCorrect', 'PRON'): 2,
  ('LeftCorrect', 'ADP'): 2,
  ('LeftIncorrect', 'MASKED'): 1,
  ('LeftIncorrect', 'PRON'): 1,
  ('LeftCorrect', 'NOUN'): 3,
  ('Improved', 'CCONJ'): 1},
 {('LeftCorrect', 'PRON'): 1,
  ('LeftCorrect', 'AUX'): 1,
  ('LeftCorrect', 'DET'): 3,
  ('LeftCorrect', 'PROPN'): 1,
  ('LeftCorrect', 'CCONJ'): 1,
  ('LeftCorrect', 'NOUN'): 2,
  ('LeftCorrect', 'ADP'): 1},
 {('LeftCorrect', 'ADV'): 2,
  ('LeftCorrect', 'VERB'): 5,
  ('LeftCorrect', 'NOUN'): 6,
  ('LeftCorrect', 'PRON'): 5,
  ('LeftCorrect', 'SCONJ'): 2,
  ('LeftCorrect', 'ADJ'): 3,
  ('LeftCorrect', 'AUX'): 1,
  ('LeftIncorrect', 'DET'): 1,
  ('LeftIncorrect', 'ADJ'): 1,
  ('LeftIncorrect', 'NOUN'): 1,
  ('LeftCorrect', 'ADP'): 3,
  ('LeftCorrect', 'CCONJ'): 1,
  ('LeftCorrect', 'DET'): 2,
  ('Improved', 'NOUN'): 1},
 {('LeftCorrect', 'PRON'): 2,
  ('LeftCorrect', 'VERB'): 1,
  ('LeftCorrect', 'DET'): 2,
  ('LeftCorrect', 'ADJ'): 1,
  ('LeftCorrect', 'NOUN'): 2,
  ('LeftCorrect', 'AUX'): 1,
  ('LeftCorrect', 'ADV'): 1},
 {('LeftCorrect', 'VERB'): 5,
  ('LeftCorrect', 'PRON'): 6,
  ('LeftCorrect', 'NOUN'): 7,
  ('LeftCorrect', 'PART'): 1,
  ('LeftCorrect', 'DET'): 6,
  ('Improved', 'NOUN'): 2,
  ('LeftCorrect', 'ADP'): 5,
  ('LeftCorrect', 'ADV'): 1,
  ('LeftCorrect', 'CCONJ'): 1,
  ('LeftCorrect', 'SCONJ'): 1,
  ('Improved', 'DET'): 1,
  ('LeftCorrect', 'AUX'): 1,
  ('LeftCorrect', 'ADJ'): 1,
  ('LeftCorrect', 'PROPN'): 2},
 {('LeftCorrect', 'DET'): 3,
  ('LeftCorrect', 'NOUN'): 10,
  ('LeftCorrect', 'AUX'): 2,
  ('LeftCorrect', 'ADJ'): 3,
  ('LeftCorrect', 'ADP'): 4,
  ('Improved', 'CCONJ'): 1,
  ('LeftCorrect', 'VERB'): 1,
  ('Improved', 'DET'): 1,
  ('LeftCorrect', 'CCONJ'): 2},
 {('LeftCorrect', 'AUX'): 1,
  ('LeftCorrect', 'PRON'): 3,
  ('LeftCorrect', 'PART'): 1,
  ('LeftCorrect', 'VERB'): 2,
  ('LeftCorrect', 'ADP'): 1,
  ('Improved', 'NOUN'): 1,
  ('LeftCorrect', 'ADV'): 1},
 {('LeftCorrect', 'PRON'): 3,
  ('LeftCorrect', 'VERB'): 3,
  ('LeftCorrect', 'PART'): 1,
  ('LeftCorrect', 'PROPN'): 1,
  ('LeftIncorrect', 'VERB'): 1,
  ('LeftCorrect', 'ADP'): 1},
 {('LeftCorrect', 'SCONJ'): 1,
  ('LeftCorrect', 'PRON'): 3,
  ('LeftIncorrect', 'AUX'): 2,
  ('LeftIncorrect', 'MASKED'): 2,
  ('LeftIncorrect', 'VERB'): 1,
  ('LeftCorrect', 'ADP'): 2,
  ('LeftIncorrect', 'DET'): 1,
  ('LeftIncorrect', 'NOUN'): 1,
  ('LeftIncorrect', 'ADP'): 1,
  ('LeftCorrect', 'DET'): 2,
  ('LeftCorrect', 'NOUN'): 3,
  ('LeftCorrect', 'AUX'): 1,
  ('LeftCorrect', 'ADV'): 1,
  ('LeftCorrect', 'VERB'): 2,
  ('LeftIncorrect', 'PRON'): 1,
  ('LeftCorrect', 'CCONJ'): 1},
 {('LeftCorrect', 'AUX'): 2,
  ('LeftCorrect', 'PRON'): 1,
  ('LeftCorrect', 'PART'): 1,
  ('LeftCorrect', 'ADV'): 1,
  ('LeftCorrect', 'DET'): 1,
  ('LeftCorrect', 'NOUN'): 1},
 {('LeftCorrect', 'PRON'): 3,
  ('LeftCorrect', 'VERB'): 2,
  ('LeftCorrect', 'NOUN'): 3,
  ('Improved', 'VERB'): 2,
  ('LeftCorrect', 'ADP'): 2,
  ('LeftIncorrect', 'MASKED'): 1},
 {('LeftCorrect', 'AUX'): 1,
  ('LeftCorrect', 'PART'): 1,
  ('LeftCorrect', 'SCONJ'): 1,
  ('LeftCorrect', 'ADV'): 3,
  ('LeftCorrect', 'PRON'): 1,
  ('LeftIncorrect', 'AUX'): 2,
  ('IntroducedError', 'PART'): 1,
  ('LeftCorrect', 'VERB'): 2,
  ('LeftCorrect', 'PROPN'): 1,
  ('LeftCorrect', 'ADJ'): 1,
  ('LeftCorrect', 'ADP'): 2,
  ('LeftCorrect', 'DET'): 1,
  ('LeftCorrect', 'NOUN'): 1,
  ('LeftIncorrect', 'DET'): 1,
  ('LeftIncorrect', 'NOUN'): 1},
 {('LeftCorrect', 'CCONJ'): 2,
  ('LeftCorrect', 'PRON'): 2,
  ('LeftCorrect', 'AUX'): 2,
  ('LeftCorrect', 'ADJ'): 3,
  ('LeftCorrect', 'PART'): 3,
  ('LeftCorrect', 'ADV'): 2,
  ('LeftCorrect', 'VERB'): 2,
  ('LeftCorrect', 'SCONJ'): 1,
  ('LeftCorrect', 'DET'): 2,
  ('LeftCorrect', 'NOUN'): 3,
  ('LeftCorrect', 'ADP'): 1,
  ('LeftCorrect', 'PROPN'): 1,
  ('Improved', 'ADP'): 1},
 {('LeftCorrect', 'CCONJ'): 1,
  ('LeftCorrect', 'SCONJ'): 2,
  ('LeftCorrect', 'NOUN'): 3,
  ('LeftIncorrect', 'PRON'): 1,
  ('LeftCorrect', 'PROPN'): 2,
  ('LeftCorrect', 'AUX'): 2,
  ('LeftCorrect', 'DET'): 3,
  ('Improved', 'VERB'): 1,
  ('Improved', 'DET'): 2,
  ('LeftCorrect', 'PART'): 1,
  ('LeftCorrect', 'VERB'): 2,
  ('LeftCorrect', 'ADP'): 1,
  ('Improved', 'NOUN'): 1,
  ('LeftCorrect', 'PRON'): 1},
 {('LeftCorrect', 'CCONJ'): 2,
  ('LeftCorrect', 'PRON'): 1,
  ('LeftCorrect', 'VERB'): 1,
  ('LeftCorrect', 'ADJ'): 4,
  ('LeftCorrect', 'ADP'): 8,
  ('LeftCorrect', 'DET'): 5,
  ('LeftCorrect', 'NOUN'): 7},
 {('LeftCorrect', 'PRON'): 6,
  ('LeftCorrect', 'ADV'): 3,
  ('LeftCorrect', 'VERB'): 1,
  ('LeftCorrect', 'DET'): 1,
  ('LeftCorrect', 'NOUN'): 4,
  ('LeftCorrect', 'ADP'): 3,
  ('LeftCorrect', 'AUX'): 2,
  ('LeftCorrect', 'PART'): 1,
  ('LeftCorrect', 'CCONJ'): 3,
  ('LeftIncorrect', 'PRON'): 1,
  ('LeftIncorrect', 'VERB'): 1,
  ('LeftCorrect', 'ADJ'): 3,
  ('LeftIncorrect', 'CCONJ'): 1},
 {('LeftCorrect', 'AUX'): 1,
  ('LeftCorrect', 'PRON'): 5,
  ('LeftCorrect', 'PART'): 5,
  ('LeftCorrect', 'VERB'): 5,
  ('Improved', 'PRON'): 1,
  ('Improved', 'ADP'): 1,
  ('Improved', 'ADJ'): 2,
  ('LeftIncorrect', 'MASKED'): 1,
  ('LeftCorrect', 'NOUN'): 8,
  ('LeftCorrect', 'ADP'): 5,
  ('Improved', 'NOUN'): 1,
  ('LeftIncorrect', 'ADP'): 1,
  ('LeftCorrect', 'ADJ'): 3,
  ('LeftCorrect', 'DET'): 3},
 {('LeftCorrect', 'SCONJ'): 2,
  ('LeftCorrect', 'PRON'): 2,
  ('LeftCorrect', 'AUX'): 2,
  ('LeftCorrect', 'PART'): 1,
  ('LeftCorrect', 'VERB'): 2,
  ('LeftCorrect', 'ADP'): 2,
  ('LeftCorrect', 'NOUN'): 2,
  ('Improved', 'PRON'): 1},
 {('LeftIncorrect', 'NOUN'): 1,
  ('LeftCorrect', 'NOUN'): 3,
  ('LeftIncorrect', 'CCONJ'): 1,
  ('LeftIncorrect', 'DET'): 1,
  ('LeftIncorrect', 'VERB'): 1,
  ('LeftIncorrect', 'PRON'): 1,
  ('LeftIncorrect', 'ADP'): 2,
  ('LeftCorrect', 'DET'): 1,
  ('LeftCorrect', 'AUX'): 1,
  ('LeftCorrect', 'PRON'): 1,
  ('LeftCorrect', 'VERB'): 2,
  ('LeftCorrect', 'ADP'): 2,
  ('LeftCorrect', 'CCONJ'): 1},
 {('LeftCorrect', 'INTJ'): 1,
  ('LeftCorrect', 'PRON'): 3,
  ('LeftCorrect', 'VERB'): 1,
  ('LeftCorrect', 'ADP'): 2,
  ('LeftCorrect', 'CCONJ'): 1,
  ('LeftIncorrect', 'PRON'): 1,
  ('LeftIncorrect', 'VERB'): 1,
  ('LeftCorrect', 'PART'): 2,
  ('LeftIncorrect', 'ADJ'): 1,
  ('Improved', 'ADP'): 1,
  ('LeftCorrect', 'AUX'): 2,
  ('LeftCorrect', 'DET'): 1,
  ('LeftCorrect', 'NOUN'): 2,
  ('LeftCorrect', 'ADJ'): 1},
 {('LeftCorrect', 'PRON'): 3,
  ('LeftCorrect', 'VERB'): 2,
  ('Improved', 'PRON'): 1},
 {('LeftCorrect', 'VERB'): 3,
  ('LeftCorrect', 'PRON'): 5,
  ('LeftCorrect', 'NOUN'): 3,
  ('LeftCorrect', 'ADJ'): 3,
  ('LeftCorrect', 'CCONJ'): 1,
  ('LeftCorrect', 'ADP'): 3,
  ('LeftCorrect', 'AUX'): 1,
  ('LeftCorrect', 'DET'): 1},
 {('LeftCorrect', 'INTJ'): 1,
  ('LeftCorrect', 'ADV'): 2,
  ('LeftCorrect', 'CCONJ'): 1,
  ('LeftIncorrect', 'VERB'): 1,
  ('LeftCorrect', 'AUX'): 1,
  ('LeftCorrect', 'ADJ'): 1},
 {('LeftCorrect', 'SCONJ'): 1,
  ('LeftCorrect', 'PROPN'): 1,
  ('LeftCorrect', 'VERB'): 2,
  ('LeftCorrect', 'DET'): 4,
  ('LeftCorrect', 'ADJ'): 1,
  ('LeftCorrect', 'NOUN'): 4,
  ('LeftCorrect', 'PART'): 1,
  ('LeftCorrect', 'ADP'): 1,
  ('Improved', 'CCONJ'): 1,
  ('LeftCorrect', 'AUX'): 1,
  ('LeftCorrect', 'PRON'): 1,
  ('Improved', 'ADV'): 1},
 {('LeftCorrect', 'DET'): 3,
  ('LeftIncorrect', 'NOUN'): 2,
  ('LeftCorrect', 'ADP'): 2,
  ('LeftCorrect', 'NOUN'): 4,
  ('LeftCorrect', 'VERB'): 2,
  ('LeftCorrect', 'SCONJ'): 1,
  ('LeftIncorrect', 'ADJ'): 1,
  ('LeftCorrect', 'PART'): 1},
 {('LeftIncorrect', 'DET'): 2,
  ('LeftCorrect', 'ADJ'): 2,
  ('LeftIncorrect', 'NOUN'): 2,
  ('LeftIncorrect', 'MASKED'): 1,
  ('LeftCorrect', 'AUX'): 1,
  ('LeftIncorrect', 'AUX'): 1,
  ('LeftIncorrect', 'PRON'): 2,
  ('LeftIncorrect', 'ADP'): 1,
  ('IntroducedError', 'ADJ'): 1,
  ('LeftCorrect', 'NOUN'): 5,
  ('LeftCorrect', 'CCONJ'): 2,
  ('LeftCorrect', 'VERB'): 1,
  ('LeftCorrect', 'ADP'): 3,
  ('LeftCorrect', 'DET'): 1,
  ('LeftCorrect', 'PART'): 1},
 {('LeftCorrect', 'ADV'): 2,
  ('LeftIncorrect', 'ADP'): 1,
  ('LeftIncorrect', 'DET'): 1,
  ('LeftIncorrect', 'NOUN'): 1,
  ('LeftCorrect', 'PRON'): 1,
  ('Improved', 'AUX'): 1,
  ('Improved', 'PART'): 1,
  ('LeftCorrect', 'VERB'): 2,
  ('LeftCorrect', 'PART'): 1,
  ('LeftCorrect', 'ADP'): 1,
  ('LeftCorrect', 'DET'): 1,
  ('LeftCorrect', 'ADJ'): 1},
 {('LeftCorrect', 'ADP'): 1,
  ('LeftCorrect', 'DET'): 3,
  ('LeftIncorrect', 'NOUN'): 3,
  ('LeftIncorrect', 'ADP'): 3,
  ('LeftCorrect', 'NOUN'): 4,
  ('LeftCorrect', 'AUX'): 2,
  ('LeftCorrect', 'ADJ'): 1,
  ('LeftIncorrect', 'CCONJ'): 1,
  ('LeftIncorrect', 'PRON'): 1,
  ('LeftIncorrect', 'AUX'): 1,
  ('LeftCorrect', 'VERB'): 2,
  ('LeftIncorrect', 'VERB'): 1},
 {('LeftCorrect', 'DET'): 3,
  ('LeftCorrect', 'NOUN'): 3,
  ('LeftCorrect', 'ADP'): 3,
  ('LeftIncorrect', 'MASKED'): 1,
  ('LeftIncorrect', 'VERB'): 1,
  ('LeftCorrect', 'VERB'): 2,
  ('LeftCorrect', 'PROPN'): 1,
  ('LeftCorrect', 'AUX'): 2,
  ('LeftCorrect', 'ADJ'): 1,
  ('Improved', 'VERB'): 1,
  ('LeftIncorrect', 'NOUN'): 1},
 {('LeftCorrect', 'CCONJ'): 1,
  ('LeftCorrect', 'PRON'): 2,
  ('LeftCorrect', 'AUX'): 3,
  ('LeftCorrect', 'ADV'): 1,
  ('LeftCorrect', 'DET'): 1,
  ('LeftCorrect', 'NOUN'): 1,
  ('LeftCorrect', 'PART'): 1,
  ('LeftIncorrect', 'NOUN'): 1,
  ('LeftCorrect', 'VERB'): 1},
 {('LeftCorrect', 'PART'): 1,
  ('LeftCorrect', 'VERB'): 7,
  ('LeftCorrect', 'DET'): 11,
  ('LeftCorrect', 'NOUN'): 20,
  ('LeftCorrect', 'CCONJ'): 2,
  ('LeftCorrect', 'ADP'): 15,
  ('LeftCorrect', 'PRON'): 9,
  ('LeftCorrect', 'ADJ'): 7,
  ('LeftIncorrect', 'PRON'): 1,
  ('LeftIncorrect', 'ADP'): 2,
  ('LeftIncorrect', 'MASKED'): 1,
  ('LeftIncorrect', 'NOUN'): 1,
  ('LeftIncorrect', 'CCONJ'): 1,
  ('LeftIncorrect', 'VERB'): 1},
 {('LeftCorrect', 'PRON'): 4,
  ('LeftCorrect', 'AUX'): 1,
  ('LeftCorrect', 'NOUN'): 6,
  ('LeftCorrect', 'VERB'): 3,
  ('LeftCorrect', 'DET'): 2,
  ('LeftCorrect', 'ADP'): 2,
  ('LeftCorrect', 'CCONJ'): 1,
  ('LeftIncorrect', 'ADJ'): 1},
 {('LeftCorrect', 'PRON'): 2,
  ('LeftCorrect', 'VERB'): 2,
  ('LeftCorrect', 'ADJ'): 1,
  ('LeftCorrect', 'SCONJ'): 1},
 {('LeftCorrect', 'AUX'): 1,
  ('LeftCorrect', 'PROPN'): 1,
  ('LeftCorrect', 'DET'): 1,
  ('LeftCorrect', 'NOUN'): 1},
 {('LeftCorrect', 'PRON'): 1,
  ('LeftCorrect', 'VERB'): 1,
  ('LeftIncorrect', 'DET'): 1,
  ('LeftCorrect', 'NOUN'): 3,
  ('IntroducedError', 'ADP'): 1,
  ('LeftCorrect', 'DET'): 1,
  ('LeftCorrect', 'ADP'): 1},
 {('LeftCorrect', 'PRON'): 2,
  ('LeftIncorrect', 'VERB'): 1,
  ('LeftCorrect', 'DET'): 1,
  ('LeftCorrect', 'NOUN'): 6,
  ('LeftCorrect', 'ADP'): 3,
  ('Improved', 'PRON'): 1,
  ('LeftCorrect', 'CCONJ'): 2,
  ('LeftCorrect', 'ADJ'): 2},
 {('LeftCorrect', 'PRON'): 2,
  ('LeftIncorrect', 'VERB'): 1,
  ('LeftCorrect', 'DET'): 2,
  ('LeftCorrect', 'NOUN'): 2,
  ('LeftCorrect', 'VERB'): 1,
  ('LeftCorrect', 'ADP'): 2},
 {('LeftCorrect', 'NOUN'): 2,
  ('LeftCorrect', 'AUX'): 2,
  ('LeftCorrect', 'PART'): 1,
  ('LeftCorrect', 'VERB'): 2,
  ('LeftCorrect', 'SCONJ'): 1},
 {('LeftCorrect', 'DET'): 4,
  ('LeftCorrect', 'NOUN'): 3,
  ('LeftCorrect', 'AUX'): 1,
  ('LeftCorrect', 'ADP'): 1,
  ('Improved', 'NOUN'): 1,
  ('LeftCorrect', 'CCONJ'): 1,
  ('LeftIncorrect', 'NOUN'): 1,
  ('Improved', 'ADP'): 1},
 {('LeftCorrect', 'PRON'): 2,
  ('LeftCorrect', 'NOUN'): 4,
  ('Improved', 'AUX'): 1,
  ('LeftCorrect', 'PART'): 2,
  ('LeftCorrect', 'ADV'): 1,
  ('LeftCorrect', 'VERB'): 3,
  ('LeftCorrect', 'DET'): 2,
  ('LeftCorrect', 'ADJ'): 1,
  ('LeftCorrect', 'SCONJ'): 1,
  ('LeftCorrect', 'AUX'): 1,
  ('LeftCorrect', 'ADP'): 1},
 {('LeftCorrect', 'DET'): 2,
  ('LeftCorrect', 'NOUN'): 3,
  ('LeftCorrect', 'AUX'): 1,
  ('LeftCorrect', 'ADP'): 1},
 {('LeftIncorrect', 'VERB'): 1,
  ('LeftIncorrect', 'ADP'): 2,
  ('LeftCorrect', 'NOUN'): 2,
  ('LeftCorrect', 'VERB'): 1},
 {('LeftCorrect', 'ADP'): 4,
  ('LeftCorrect', 'DET'): 4,
  ('LeftCorrect', 'NOUN'): 5,
  ('LeftCorrect', 'PRON'): 1,
  ('LeftCorrect', 'VERB'): 1,
  ('LeftCorrect', 'PART'): 1},
 {('LeftCorrect', 'NOUN'): 3,
  ('LeftCorrect', 'AUX'): 1,
  ('LeftCorrect', 'DET'): 2,
  ('LeftCorrect', 'ADP'): 1},
 {('LeftCorrect', 'DET'): 1,
  ('LeftCorrect', 'ADJ'): 2,
  ('LeftCorrect', 'NOUN'): 2,
  ('LeftCorrect', 'PRON'): 2,
  ('LeftCorrect', 'AUX'): 3,
  ('LeftCorrect', 'VERB'): 1,
  ('LeftCorrect', 'PART'): 1},
 {('LeftCorrect', 'PRON'): 2,
  ('LeftCorrect', 'AUX'): 2,
  ('LeftCorrect', 'NOUN'): 3,
  ('LeftCorrect', 'CCONJ'): 1,
  ('LeftCorrect', 'DET'): 1,
  ('LeftCorrect', 'VERB'): 1,
  ('LeftCorrect', 'ADP'): 1},
 {('LeftCorrect', 'VERB'): 2,
  ('LeftCorrect', 'PRON'): 2,
  ('LeftCorrect', 'ADV'): 1,
  ('LeftCorrect', 'ADP'): 2,
  ('LeftCorrect', 'DET'): 2,
  ('LeftCorrect', 'NOUN'): 2},
 {('LeftCorrect', 'ADP'): 4,
  ('LeftCorrect', 'ADJ'): 1,
  ('LeftCorrect', 'NOUN'): 13,
  ('LeftCorrect', 'PRON'): 3,
  ('LeftCorrect', 'VERB'): 4,
  ('LeftCorrect', 'PART'): 2,
  ('Improved', 'SCONJ'): 1,
  ('LeftCorrect', 'DET'): 10,
  ('LeftCorrect', 'PROPN'): 1,
  ('LeftCorrect', 'AUX'): 3,
  ('LeftCorrect', 'ADV'): 2,
  ('LeftCorrect', 'CCONJ'): 3,
  ('LeftIncorrect', 'NOUN'): 2,
  ('LeftIncorrect', 'MASKED'): 1},
 {('LeftCorrect', 'ADV'): 1,
  ('LeftCorrect', 'PRON'): 2,
  ('LeftCorrect', 'VERB'): 2,
  ('LeftCorrect', 'DET'): 2,
  ('LeftCorrect', 'NOUN'): 2,
  ('LeftCorrect', 'SCONJ'): 1,
  ('LeftCorrect', 'AUX'): 1,
  ('LeftCorrect', 'ADP'): 1},
 {('LeftCorrect', 'DET'): 3,
  ('LeftCorrect', 'NOUN'): 7,
  ('LeftCorrect', 'ADP'): 4,
  ('LeftCorrect', 'ADJ'): 5,
  ('LeftCorrect', 'AUX'): 2,
  ('LeftCorrect', 'VERB'): 2,
  ('LeftIncorrect', 'ADP'): 1,
  ('LeftIncorrect', 'DET'): 1,
  ('Improved', 'DET'): 1,
  ('Improved', 'ADP'): 1,
  ('LeftCorrect', 'PROPN'): 1,
  ('Improved', 'NOUN'): 2,
  ('LeftCorrect', 'CCONJ'): 1,
  ('LeftCorrect', 'PART'): 1,
  ('LeftCorrect', 'ADV'): 2,
  ('LeftCorrect', 'PRON'): 1},
 {('LeftCorrect', 'SCONJ'): 1,
  ('LeftCorrect', 'PRON'): 2,
  ('LeftCorrect', 'VERB'): 2,
  ('LeftCorrect', 'ADP'): 2,
  ('LeftCorrect', 'DET'): 1,
  ('LeftCorrect', 'ADV'): 1,
  ('LeftCorrect', 'ADJ'): 2,
  ('LeftCorrect', 'NOUN'): 2,
  ('LeftIncorrect', 'ADP'): 1,
  ('LeftCorrect', 'PROPN'): 1},
 {('LeftCorrect', 'SCONJ'): 1,
  ('LeftIncorrect', 'AUX'): 1,
  ('LeftCorrect', 'NOUN'): 2,
  ('LeftCorrect', 'ADP'): 2,
  ('LeftIncorrect', 'MASKED'): 1,
  ('LeftCorrect', 'ADJ'): 1,
  ('IntroducedError', 'NOUN'): 1,
  ('LeftCorrect', 'PART'): 1,
  ('LeftCorrect', 'VERB'): 1,
  ('LeftCorrect', 'PRON'): 1},
 {('LeftCorrect', 'SCONJ'): 2,
  ('LeftIncorrect', 'MASKED'): 1,
  ('LeftIncorrect', 'PRON'): 1,
  ('LeftIncorrect', 'VERB'): 1,
  ('LeftCorrect', 'ADV'): 1,
  ('LeftCorrect', 'ADP'): 3,
  ('LeftCorrect', 'DET'): 4,
  ('LeftCorrect', 'PROPN'): 1,
  ('LeftCorrect', 'NOUN'): 4,
  ('LeftCorrect', 'AUX'): 1,
  ('LeftCorrect', 'VERB'): 2,
  ('LeftCorrect', 'PRON'): 1,
  ('Improved', 'ADV'): 1,
  ('Improved', 'ADP'): 1,
  ('Improved', 'ADJ'): 1},
 {('LeftCorrect', 'DET'): 1,
  ('LeftCorrect', 'PROPN'): 1,
  ('LeftIncorrect', 'PROPN'): 1,
  ('LeftCorrect', 'AUX'): 1,
  ('LeftCorrect', 'VERB'): 1,
  ('LeftIncorrect', 'DET'): 1,
  ('LeftCorrect', 'ADJ'): 1,
  ('LeftCorrect', 'NOUN'): 1},
 {('LeftIncorrect', 'SCONJ'): 1,
  ('LeftCorrect', 'ADP'): 3,
  ('LeftCorrect', 'DET'): 1,
  ('LeftCorrect', 'NOUN'): 3,
  ('LeftCorrect', 'VERB'): 1,
  ('LeftIncorrect', 'DET'): 2,
  ('IntroducedError', 'VERB'): 1,
  ('LeftCorrect', 'ADJ'): 1,
  ('IntroducedError', 'NOUN'): 1,
  ('LeftIncorrect', 'ADJ'): 1,
  ('LeftIncorrect', 'NOUN'): 1,
  ('LeftIncorrect', 'NUM'): 1},
 {('LeftCorrect', 'ADV'): 1,
  ('LeftCorrect', 'PROPN'): 7,
  ('LeftCorrect', 'VERB'): 5,
  ('LeftCorrect', 'SCONJ'): 1,
  ('Improved', 'PRON'): 1,
  ('Improved', 'VERB'): 1,
  ('LeftCorrect', 'DET'): 4,
  ('LeftCorrect', 'ADJ'): 1,
  ('LeftCorrect', 'NOUN'): 7,
  ('LeftCorrect', 'ADP'): 5,
  ('LeftCorrect', 'CCONJ'): 2,
  ('LeftCorrect', 'PRON'): 1,
  ('LeftIncorrect', 'PROPN'): 1,
  ('LeftCorrect', 'PART'): 1},
 {('LeftCorrect', 'ADJ'): 2,
  ('LeftCorrect', 'PROPN'): 1,
  ('LeftCorrect', 'VERB'): 4,
  ('LeftCorrect', 'PART'): 2,
  ('LeftCorrect', 'ADP'): 3,
  ('LeftCorrect', 'DET'): 9,
  ('LeftCorrect', 'NOUN'): 11,
  ('LeftCorrect', 'CCONJ'): 2,
  ('LeftCorrect', 'ADV'): 3,
  ('LeftCorrect', 'SCONJ'): 2,

In [ ]:

# non-parallelized approach
# tokenizer_fn = lambda s: [token.text for token in nlp(s)]
# results = []
# for asr, ref, llm in tqdm(zip(transcriptions,reference_transcriptions,corrected_transcriptions), 
#                          total=len(transcriptions)):
#     d = preprocess(ref, asr, llm, tokenizer_fn)
#     results.append(d)

In [11]:
accumulated_dict = {}

for dictionary in results:
    for key, value in dictionary.items():
        if key in accumulated_dict:
            accumulated_dict[key] += value
        else:
            accumulated_dict[key] = value

In [94]:
keys, _ = zip(*accumulated_dict.items())
ops, poses = zip(*keys)

df = pd.DataFrame(0, columns=np.unique(ops), index=np.unique(poses))
for (op,pos), val in accumulated_dict.items():
    percnt = pos
    df.loc[pos, op] += val

df

        Improved  IntroducedError  LeftCorrect  LeftIncorrect
ADJ          116               36         2891            408
ADP          162               50         5143            489
ADV           61               26         2676            280
AUX           69               20         3148            351
CCONJ         46                4         1990            201
DET          131               34         4304            525
INTJ           1                0          175             52
MASKED         0                0            0            830
NOUN         522               89         7340           1595
NUM           17                3          230             91
PART          30                9         1326            108
PRON         114               37         6578            588
PROPN         84                7          631            570
PUNCT          0                0            6              0
SCONJ         21               11         1328            113
SYM            0                0            0              1
VERB         290               70         5914           1006
X              2                0           11              6

In [95]:
df = df.drop(["MASKED","X","SYM","PUNCT"])#.assign(percentage=lambda df_: df_.sum(1))

df

       Improved  IntroducedError  LeftCorrect  LeftIncorrect
ADJ         116               36         2891            408
ADP         162               50         5143            489
ADV          61               26         2676            280
AUX          69               20         3148            351
CCONJ        46                4         1990            201
DET         131               34         4304            525
INTJ          1                0          175             52
NOUN        522               89         7340           1595
NUM          17                3          230             91
PART         30                9         1326            108
PRON        114               37         6578            588
PROPN        84                7          631            570
SCONJ        21               11         1328            113
VERB        290               70         5914           1006

In [97]:
df_1 = (df.div(df.sum(1), axis=0)*100).round(2)
df_1

       Improved  IntroducedError  LeftCorrect  LeftIncorrect
ADJ        3.36             1.04        83.77          11.82
ADP        2.77             0.86        88.00           8.37
ADV        2.00             0.85        87.94           9.20
AUX        1.92             0.56        87.74           9.78
CCONJ      2.05             0.18        88.80           8.97
DET        2.62             0.68        86.18          10.51
INTJ       0.44             0.00        76.75          22.81
NOUN       5.47             0.93        76.89          16.71
NUM        4.99             0.88        67.45          26.69
PART       2.04             0.61        90.02           7.33
PRON       1.56             0.51        89.90           8.04
PROPN      6.50             0.54        48.84          44.12
SCONJ      1.43             0.75        90.16           7.67
VERB       3.98             0.96        81.24          13.82

In [87]:
# pctn = df.sum(0).sum()
# df_1 = df_1.assign(Percentage=(df.sum(1)/pctn).round(2)*100)

In [98]:
df_1

       Improved  IntroducedError  LeftCorrect  LeftIncorrect
ADJ        3.36             1.04        83.77          11.82
ADP        2.77             0.86        88.00           8.37
ADV        2.00             0.85        87.94           9.20
AUX        1.92             0.56        87.74           9.78
CCONJ      2.05             0.18        88.80           8.97
DET        2.62             0.68        86.18          10.51
INTJ       0.44             0.00        76.75          22.81
NOUN       5.47             0.93        76.89          16.71
NUM        4.99             0.88        67.45          26.69
PART       2.04             0.61        90.02           7.33
PRON       1.56             0.51        89.90           8.04
PROPN      6.50             0.54        48.84          44.12
SCONJ      1.43             0.75        90.16           7.67
VERB       3.98             0.96        81.24          13.82

In [99]:
df_1.index = df_1.index.map(lambda idx: spacy.explain(idx))

df_1

,Improved,IntroducedError,LeftCorrect,LeftIncorrect
adjective,3.36,1.04,83.77,11.82
adposition,2.77,0.86,88.00,8.37
adverb,2.00,0.85,87.94,9.20
auxiliary,1.92,0.56,87.74,9.78
coordinating conjunction,2.05,0.18,88.80,8.97
determiner,2.62,0.68,86.18,10.51
interjection,0.44,0.00,76.75,22.81
noun,5.47,0.93,76.89,16.71
numeral,4.99,0.88,67.45,26.69
particle,2.04,0.61,90.02,7.33
pronoun,1.56,0.51,89.90,8.04
proper noun,6.50,0.54,48.84,44.12
subordinating conjunction,1.43,0.75,90.16,7.67
verb,3.98,0.96,81.24,13.82

In [100]:
print(df_1.to_latex(float_format="{:.2f}".format))

\begin{tabular}{lrrrr}
\toprule
 & Improved & IntroducedError & LeftCorrect & LeftIncorrect \\
\midrule
adjective & 3.36 & 1.04 & 83.77 & 11.82 \\
adposition & 2.77 & 0.86 & 88.00 & 8.37 \\
adverb & 2.00 & 0.85 & 87.94 & 9.20 \\
auxiliary & 1.92 & 0.56 & 87.74 & 9.78 \\
coordinating conjunction & 2.05 & 0.18 & 88.80 & 8.97 \\
determiner & 2.62 & 0.68 & 86.18 & 10.51 \\
interjection & 0.44 & 0.00 & 76.75 & 22.81 \\
noun & 5.47 & 0.93 & 76.89 & 16.71 \\
numeral & 4.99 & 0.88 & 67.45 & 26.69 \\
particle & 2.04 & 0.61 & 90.02 & 7.33 \\
pronoun & 1.56 & 0.51 & 89.90 & 8.04 \\
proper noun & 6.50 & 0.54 & 48.84 & 44.12 \\
subordinating conjunction & 1.43 & 0.75 & 90.16 & 7.67 \\
verb & 3.98 & 0.96 & 81.24 & 13.82 \\
\bottomrule
\end{tabular}

In [108]:
pctn = df.sum(1).sum()
sum_of_modifications = df.sum(1)
pctn, sum_of_modifications

(52111,
 ADJ      3451
 ADP      5844
 ADV      3043
 AUX      3588
 CCONJ    2241
 DET      4994
 INTJ      228
 NOUN     9546
 NUM       341
 PART     1473
 PRON     7317
 PROPN    1292
 SCONJ    1473
 VERB     7280
 dtype: int64)

In [121]:
df_2 = (df.div(df.sum(0)).assign(Percentage=sum_of_modifications/pctn)*100).round(2)
df_2

       Improved  IntroducedError  LeftCorrect  LeftIncorrect  Percentage
ADJ        6.97             9.09         6.62           6.40        6.62
ADP        9.74            12.63        11.78           7.67       11.21
ADV        3.67             6.57         6.13           4.39        5.84
AUX        4.15             5.05         7.21           5.50        6.89
CCONJ      2.76             1.01         4.56           3.15        4.30
DET        7.87             8.59         9.85           8.23        9.58
INTJ       0.06             0.00         0.40           0.82        0.44
NOUN      31.37            22.47        16.81          25.01       18.32
NUM        1.02             0.76         0.53           1.43        0.65
PART       1.80             2.27         3.04           1.69        2.83
PRON       6.85             9.34        15.06           9.22       14.04
PROPN      5.05             1.77         1.44           8.94        2.48
SCONJ      1.26             2.78         3.04           1.77        2.83
VERB      17.43            17.68        13.54          15.78       13.97

In [124]:
df_2.index = df_2.index.map(lambda idx: spacy.explain(idx))
print(df_2.to_latex(float_format='{:0.2f}'.format))

\begin{tabular}{lrrrrr}
\toprule
 & Improved & IntroducedError & LeftCorrect & LeftIncorrect & Percentage \\
\midrule
adjective & 6.97 & 9.09 & 6.62 & 6.40 & 6.62 \\
adposition & 9.74 & 12.63 & 11.78 & 7.67 & 11.21 \\
adverb & 3.67 & 6.57 & 6.13 & 4.39 & 5.84 \\
auxiliary & 4.15 & 5.05 & 7.21 & 5.50 & 6.89 \\
coordinating conjunction & 2.76 & 1.01 & 4.56 & 3.15 & 4.30 \\
determiner & 7.87 & 8.59 & 9.85 & 8.23 & 9.58 \\
interjection & 0.06 & 0.00 & 0.40 & 0.82 & 0.44 \\
noun & 31.37 & 22.47 & 16.81 & 25.01 & 18.32 \\
numeral & 1.02 & 0.76 & 0.53 & 1.43 & 0.65 \\
particle & 1.80 & 2.27 & 3.04 & 1.69 & 2.83 \\
pronoun & 6.85 & 9.34 & 15.06 & 9.22 & 14.04 \\
proper noun & 5.05 & 1.77 & 1.44 & 8.94 & 2.48 \\
subordinating conjunction & 1.26 & 2.78 & 3.04 & 1.77 & 2.83 \\
verb & 17.43 & 17.68 & 13.54 & 15.78 & 13.97 \\
\bottomrule
\end{tabular}

## old method

In [115]:
sequences = [
    #REF, ASR, LLM
    ("short one here", "shoe order one here", "shorts one her"),
    ("I eat salami pizza salami", "I meat a salami pizza salami", "I eat a big pizza"),
    ("their fingers sear me like scorching fire","their fingers see her me like fire","their fingers sear me like scorching fire")
]

In [66]:
ref,asr,llm = sequences[2]
def print_alignment_1(tuplee):
    tuplee = tuple(map(lambda x: [r if r else '***' for r in x ], (tuplee)))
    for t,x in zip(('REF','ASR','LLM'),tuplee):
        print(f"{t}: {' '.join(x)}")
        
print_alignment_1(align3(ref, asr, llm))

REF: their fingers *** sear me like fire
ASR: their fingers see her me like fire
LLM: their fingers *** sear me like fire

In [68]:
' '.join([t.pos_ for t in nlp("their fingers sear me like fire")])

'PRON NOUN VERB PRON ADP NOUN'

## debug

In [154]:
tokenizer_fn = lambda s: [token.text for token in nlp(s)]
ref, asr, llm = sequences[2]
edit_types, edits, operations = identify_edit_type(ref, asr, llm, tokenizer_fn=tokenizer_fn)

In [157]:
# debug
print('ref: ',ref)
print('asr: ', asr)
print('llm: ', llm)
align3(ref,asr,llm, tokenizer_fn=tokenizer_fn)

ref:  their fingers sear me like scorching fire
asr:  their fingers see her me like fire
llm:  their fingers sear me like scorching fire

(['their', 'fingers', '', 'sear', 'me', 'like', 'scorching', 'fire'],
 ['their', 'fingers', 'see', 'her', 'me', 'like', '', 'fire'],
 ['their', 'fingers', '', 'sear', 'me', 'like', 'scorching', 'fire'])

In [158]:
# debug
edits

{'Improved': [('see', '', ''),
  ('her', 'sear', 'sear'),
  ('', 'scorching', 'scorching')],
 'IntroducedError': [],
 'LeftCorrect': [('their', 'their', 'their'),
  ('fingers', 'fingers', 'fingers'),
  ('me', 'me', 'me'),
  ('like', 'like', 'like'),
  ('fire', 'fire', 'fire')],
 'LeftIncorrect': []}

In [159]:
# debug
edit_types

['LeftCorrect',
 'LeftCorrect',
 'Improved',
 'Improved',
 'LeftCorrect',
 'LeftCorrect',
 'Improved',
 'LeftCorrect']

In [160]:
# debug
operations

['-', '-', 'D', 'S', '-', '-', 'I', '-']

In [161]:
ref_al, asr_al, llm_al = align3(ref,asr,llm, tokenizer_fn=tokenizer_fn)
ref_al, asr_al, llm_al

(['their', 'fingers', '', 'sear', 'me', 'like', 'scorching', 'fire'],
 ['their', 'fingers', 'see', 'her', 'me', 'like', '', 'fire'],
 ['their', 'fingers', '', 'sear', 'me', 'like', 'scorching', 'fire'])

In [162]:
llm_al_str = " ".join([r if r else "*" for r in llm_al])
asr_al_str = " ".join([r if r else "*" for r in asr_al])
ref_al_str = " ".join([r if r else "*" for r in ref_al])

ref_al_str, asr_al_str, llm_al_str

('their fingers * sear me like scorching fire',
 'their fingers see her me like * fire',
 'their fingers * sear me like scorching fire')

In [169]:
l_doc = nlp(llm_al_str)
r_doc = nlp(ref_al_str)
a_doc = nlp(asr_al_str)

d = {}

assert len(l_doc) == len(a_doc) == len(r_doc)

for i in range(len(a_doc)):

    a_token = a_doc[i]
    if a_token.text == '*':
        a_pos = "MASEKD"
    else:
        a_pos = a_token.pos_
    
    l_token = l_doc[i]
    if l_token.text == '*':
        l_pos = "MASKED"
    else:
        l_pos = l_token.pos_
    
    operation = operations[i]
    edit_type = edit_types[i]

    if operation == 'I':
        pos = l_pos
    elif operation == 'D':
        pos = a_pos
    elif operation == '-':
        pos = a_pos
    elif operation == 'S':
        pos = a_pos

    
    d[(edit_type, pos)] = d.get((edit_type, pos), 0) + 1
    
    print(f"{operation=}, {edit_type=}, {a_pos=} {l_pos=}, {pos=}")

d

operation='-', edit_type='LeftCorrect', a_pos='PRON' l_pos='PRON', pos='PRON'
operation='-', edit_type='LeftCorrect', a_pos='NOUN' l_pos='NOUN', pos='NOUN'
operation='D', edit_type='Improved', a_pos='VERB' l_pos='MASKED', pos='VERB'
operation='S', edit_type='Improved', a_pos='PRON' l_pos='VERB', pos='PRON'
operation='-', edit_type='LeftCorrect', a_pos='PRON' l_pos='PRON', pos='PRON'
operation='-', edit_type='LeftCorrect', a_pos='ADP' l_pos='ADP', pos='ADP'
operation='I', edit_type='Improved', a_pos='MASEKD' l_pos='VERB', pos='VERB'
operation='-', edit_type='LeftCorrect', a_pos='NOUN' l_pos='NOUN', pos='NOUN'

{('LeftCorrect', 'PRON'): 2,
 ('LeftCorrect', 'NOUN'): 2,
 ('Improved', 'VERB'): 2,
 ('Improved', 'PRON'): 1,
 ('LeftCorrect', 'ADP'): 1}

In [218]:
keys, values = zip(*d.items())
ops, poses = zip(*keys)

df = pd.DataFrame(0, columns=np.unique(ops), index=np.unique(poses))
for (op,pos), value in d.items():
    df.loc[pos, op] += value

df

      Improved  LeftCorrect
ADP          0            1
NOUN         0            2
PRON         1            2
VERB         2            0

In [ ]:
# deletion => pos (asr)
# insert => pos (llm)
# substitute => pos (llm)

In [146]:
align3(ref,asr,llm, tokenizer_fn=tokenizer_fn)

(['their', 'fingers', '', 'sear', 'me', 'like', 'scorching', 'fire'],
 ['their', 'fingers', 'see', 'her', 'me', 'like', '', 'fire'],
 ['their', 'fingers', '', 'sear', 'me', 'like', 'scorching', 'fire'])

In [78]:
poses = [t.pos_ for t in nlp(llm)]
poses

['PRON', 'NOUN', 'VERB', 'PRON', 'ADP', 'NOUN']

In [86]:
len(edit_types), len(poses)

(7, 6)

In [88]:
ref_al, asr_al, llm_al = align3(ref,asr,llm)
ref_al, asr_al, llm_al

(['their', 'fingers', '', 'sear', 'me', 'like', 'fire'],
 ['their', 'fingers', 'see', 'her', 'me', 'like', 'fire'],
 ['their', 'fingers', '', 'sear', 'me', 'like', 'fire'])

In [104]:
llm_al_str = " ".join([r if r else "*" for r in llm_al])
llm_al_str

'their fingers * sear me like fire'

In [105]:
llm_al_str_pos = [t.pos_ for t in nlp(llm_al_str)]
llm_al_str_pos

['PRON', 'NOUN', 'PUNCT', 'VERB', 'PRON', 'ADP', 'NOUN']

In [108]:
result = []
for token, modification in zip(nlp(llm_al_str), edit_types):
    if token.text == "*":
        pos_tag = "MASKED"
    else:
        pos_tag = token.pos_
    result.append((modification, pos_tag, token.text))

result

[('LeftCorrect', 'PRON', 'their'),
 ('LeftCorrect', 'NOUN', 'fingers'),
 ('Improved', 'MASKED', '*'),
 ('Improved', 'VERB', 'sear'),
 ('LeftCorrect', 'PRON', 'me'),
 ('LeftCorrect', 'ADP', 'like'),
 ('LeftCorrect', 'NOUN', 'fire')]

In [107]:
doc = nlp(llm_al_str)
[(token.text, token.pos_) for token in doc]

[('their', 'PRON'),
 ('fingers', 'NOUN'),
 ('*', 'PUNCT'),
 ('sear', 'VERB'),
 ('me', 'PRON'),
 ('like', 'ADP'),
 ('fire', 'NOUN')]

In [151]:
import sys
!{sys.executable} -m pip install -U pip install --upgrade torchaudio torch==2.0.1 flair

Requirement already satisfied: pip in /home/mnaderi/.local/lib/python3.10/site-packages (24.0)
Collecting install
  Downloading install-1.3.5-py3-none-any.whl.metadata (925 bytes)
Requirement already satisfied: torchaudio in /home/mnaderi/miniconda3/lib/python3.10/site-packages (2.0.2)
Collecting torchaudio
  Downloading torchaudio-2.3.1-cp310-cp310-manylinux1_x86_64.whl.metadata (6.4 kB)
Collecting torch==2.0.1
  Downloading torch-2.0.1-cp310-cp310-manylinux1_x86_64.whl.metadata (24 kB)
Requirement already satisfied: flair in /home/mnaderi/miniconda3/lib/python3.10/site-packages (0.13.1)
Requirement already satisfied: filelock in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from torch==2.0.1) (3.12.4)
Requirement already satisfied: typing-extensions in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from torch==2.0.1) (4.12.2)
Requirement already satisfied: sympy in /home/mnaderi/.local/lib/python3.10/site-packages (from torch==2.0.1) (1.12)
Requirement already satisfied: networkx in /home/mnaderi/.local/lib/python3.10/site-packages (from torch==2.0.1) (3.1)
Requirement already satisfied: jinja2 in /home/mnaderi/.local/lib/python3.10/site-packages (from torch==2.0.1) (3.1.2)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in /home/mnaderi/.local/lib/python3.10/site-packages (from torch==2.0.1) (11.7.99)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in /home/mnaderi/.local/lib/python3.10/site-packages (from torch==2.0.1) (11.7.99)
Requirement already satisfied: nvidia-cuda-cupti-cu11==11.7.101 in /home/mnaderi/.local/lib/python3.10/site-packages (from torch==2.0.1) (11.7.101)
Requirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in /home/mnaderi/.local/lib/python3.10/site-packages (from torch==2.0.1) (8.5.0.96)
Requirement already satisfied: nvidia-cublas-cu11==11.10.3.66 in /home/mnaderi/.local/lib/python3.10/site-packages (from torch==2.0.1) (11.10.3.66)
Requirement already satisfied: nvidia-cufft-cu11==10.9.0.58 in /home/mnaderi/.local/lib/python3.10/site-packages (from torch==2.0.1) (10.9.0.58)
Requirement already satisfied: nvidia-curand-cu11==10.2.10.91 in /home/mnaderi/.local/lib/python3.10/site-packages (from torch==2.0.1) (10.2.10.91)
Requirement already satisfied: nvidia-cusolver-cu11==11.4.0.1 in /home/mnaderi/.local/lib/python3.10/site-packages (from torch==2.0.1) (11.4.0.1)
Requirement already satisfied: nvidia-cusparse-cu11==11.7.4.91 in /home/mnaderi/.local/lib/python3.10/site-packages (from torch==2.0.1) (11.7.4.91)
Requirement already satisfied: nvidia-nccl-cu11==2.14.3 in /home/mnaderi/.local/lib/python3.10/site-packages (from torch==2.0.1) (2.14.3)
Requirement already satisfied: nvidia-nvtx-cu11==11.7.91 in /home/mnaderi/.local/lib/python3.10/site-packages (from torch==2.0.1) (11.7.91)
Collecting triton==2.0.0 (from torch==2.0.1)
  Downloading triton-2.0.0-1-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.0 kB)
Requirement already satisfied: setuptools in /home/mnaderi/.local/lib/python3.10/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch==2.0.1) (69.1.1)
Requirement already satisfied: wheel in /home/mnaderi/.local/lib/python3.10/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch==2.0.1) (0.42.0)
Requirement already satisfied: cmake in /home/mnaderi/.local/lib/python3.10/site-packages (from triton==2.0.0->torch==2.0.1) (3.27.5)
Requirement already satisfied: lit in /home/mnaderi/.local/lib/python3.10/site-packages (from triton==2.0.0->torch==2.0.1) (17.0.1)
INFO: pip is looking at multiple versions of torchaudio to determine which version is compatible with other requirements. This could take a while.
Collecting torchaudio
  Downloading torchaudio-2.3.0-cp310-cp310-manylinux1_x86_64.whl.metadata (6.4 kB)
  Downloading torchaudio-2.2.2-cp310-cp310-manylinux1_x86_64.whl.metadata (6.4 kB)
  Downloading torchaudio-2.2.1-cp310-cp310-manylinux1_x86_64.whl.metadata (6.4 kB)
  Downloading torchaudio-2.2.0-cp310-cp310-manylinux1_x86_64.whl.metadata (6.4 kB)
  Downloading torchaudio-2.1.2-cp310-cp310-manylinux1_x86_64.whl.metadata (6.4 kB)
  Downloading torchaudio-2.1.1-cp310-cp310-manylinux1_x86_64.whl.metadata (6.4 kB)
  Downloading torchaudio-2.1.0-cp310-cp310-manylinux1_x86_64.whl.metadata (5.7 kB)
INFO: pip is still looking at multiple versions of torchaudio to determine which version is compatible with other requirements. This could take a while.
Requirement already satisfied: boto3>=1.20.27 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from flair) (1.34.127)
Requirement already satisfied: bpemb>=0.3.2 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from flair) (0.3.5)
Requirement already satisfied: conllu>=4.0 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from flair) (4.5.3)
Requirement already satisfied: deprecated>=1.2.13 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from flair) (1.2.14)
Requirement already satisfied: ftfy>=6.1.0 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from flair) (6.2.0)
Requirement already satisfied: gdown>=4.4.0 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from flair) (5.2.0)
Requirement already satisfied: gensim>=4.2.0 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from flair) (4.3.2)
Requirement already satisfied: huggingface-hub>=0.10.0 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from flair) (0.17.2)
Requirement already satisfied: janome>=0.4.2 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from flair) (0.5.0)
Requirement already satisfied: langdetect>=1.0.9 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from flair) (1.0.9)
Requirement already satisfied: lxml>=4.8.0 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from flair) (5.2.2)
Requirement already satisfied: matplotlib>=2.2.3 in /home/mnaderi/.local/lib/python3.10/site-packages (from flair) (3.7.2)
Requirement already satisfied: more-itertools>=8.13.0 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from flair) (10.1.0)
Requirement already satisfied: mpld3>=0.3 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from flair) (0.5.10)
Requirement already satisfied: pptree>=3.1 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from flair) (3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/mnaderi/.local/lib/python3.10/site-packages (from flair) (2.8.2)
Requirement already satisfied: pytorch-revgrad>=0.2.0 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from flair) (0.2.0)
Requirement already satisfied: regex>=2022.1.18 in /home/mnaderi/.local/lib/python3.10/site-packages (from flair) (2023.8.8)
Requirement already satisfied: scikit-learn>=1.0.2 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from flair) (1.5.0)
Requirement already satisfied: segtok>=1.5.11 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from flair) (1.5.11)
Requirement already satisfied: sqlitedict>=2.0.0 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from flair) (2.1.0)
Requirement already satisfied: tabulate>=0.8.10 in /home/mnaderi/.local/lib/python3.10/site-packages (from flair) (0.9.0)
Requirement already satisfied: tqdm>=4.63.0 in /home/mnaderi/.local/lib/python3.10/site-packages (from flair) (4.66.1)
Requirement already satisfied: transformer-smaller-training-vocab>=0.2.3 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from flair) (0.4.0)
Requirement already satisfied: transformers<5.0.0,>=4.18.0 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from transformers[sentencepiece]<5.0.0,>=4.18.0->flair) (4.33.2)
Requirement already satisfied: urllib3<2.0.0,>=1.0.0 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from flair) (1.26.16)
Requirement already satisfied: wikipedia-api>=0.5.7 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from flair) (0.6.0)
Requirement already satisfied: semver<4.0.0,>=3.0.0 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from flair) (3.0.2)
Requirement already satisfied: botocore<1.35.0,>=1.34.127 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from boto3>=1.20.27->flair) (1.34.127)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from boto3>=1.20.27->flair) (1.0.1)
Requirement already satisfied: s3transfer<0.11.0,>=0.10.0 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from boto3>=1.20.27->flair) (0.10.1)
Requirement already satisfied: numpy in /home/mnaderi/.local/lib/python3.10/site-packages (from bpemb>=0.3.2->flair) (1.25.2)
Requirement already satisfied: requests in /home/mnaderi/.local/lib/python3.10/site-packages (from bpemb>=0.3.2->flair) (2.31.0)
Requirement already satisfied: sentencepiece in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from bpemb>=0.3.2->flair) (0.2.0)
Requirement already satisfied: wrapt<2,>=1.10 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from deprecated>=1.2.13->flair) (1.16.0)
Requirement already satisfied: wcwidth<0.3.0,>=0.2.12 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from ftfy>=6.1.0->flair) (0.2.13)
Requirement already satisfied: beautifulsoup4 in /home/mnaderi/.local/lib/python3.10/site-packages (from gdown>=4.4.0->flair) (4.12.2)
Requirement already satisfied: scipy>=1.7.0 in /home/mnaderi/.local/lib/python3.10/site-packages (from gensim>=4.2.0->flair) (1.11.3)
Requirement already satisfied: smart-open>=1.8.1 in /home/mnaderi/.local/lib/python3.10/site-packages (from gensim>=4.2.0->flair) (6.4.0)
Requirement already satisfied: fsspec in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from huggingface-hub>=0.10.0->flair) (2023.9.1)
Requirement already satisfied: pyyaml>=5.1 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from huggingface-hub>=0.10.0->flair) (6.0.1)
Requirement already satisfied: packaging>=20.9 in /home/mnaderi/.local/lib/python3.10/site-packages (from huggingface-hub>=0.10.0->flair) (23.1)
Requirement already satisfied: six in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from langdetect>=1.0.9->flair) (1.16.0)
Requirement already satisfied: contourpy>=1.0.1 in /home/mnaderi/.local/lib/python3.10/site-packages (from matplotlib>=2.2.3->flair) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /home/mnaderi/.local/lib/python3.10/site-packages (from matplotlib>=2.2.3->flair) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/mnaderi/.local/lib/python3.10/site-packages (from matplotlib>=2.2.3->flair) (4.42.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/mnaderi/.local/lib/python3.10/site-packages (from matplotlib>=2.2.3->flair) (1.4.5)
Requirement already satisfied: pillow>=6.2.0 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from matplotlib>=2.2.3->flair) (10.0.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from matplotlib>=2.2.3->flair) (3.0.9)
Requirement already satisfied: joblib>=1.2.0 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from scikit-learn>=1.0.2->flair) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from scikit-learn>=1.0.2->flair) (3.5.0)
INFO: pip is looking at multiple versions of transformer-smaller-training-vocab to determine which version is compatible with other requirements. This could take a while.
Collecting transformer-smaller-training-vocab>=0.2.3 (from flair)
  Downloading transformer_smaller_training_vocab-0.3.3-py3-none-any.whl.metadata (8.0 kB)
Collecting sentencepiece (from bpemb>=0.3.2->flair)
  Downloading sentencepiece-0.1.99-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.7 kB)
Collecting transformer-smaller-training-vocab>=0.2.3 (from flair)
  Downloading transformer_smaller_training_vocab-0.3.2-py3-none-any.whl.metadata (7.9 kB)
  Downloading transformer_smaller_training_vocab-0.3.1-py3-none-any.whl.metadata (7.9 kB)
  Downloading transformer_smaller_training_vocab-0.2.4-py3-none-any.whl.metadata (7.9 kB)
Collecting datasets<3.0.0,>=2.0.0 (from transformer-smaller-training-vocab>=0.2.3->flair)
  Downloading datasets-2.20.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from transformers<5.0.0,>=4.18.0->transformers[sentencepiece]<5.0.0,>=4.18.0->flair) (0.13.3)
Requirement already satisfied: safetensors>=0.3.1 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from transformers<5.0.0,>=4.18.0->transformers[sentencepiece]<5.0.0,>=4.18.0->flair) (0.3.3)
Requirement already satisfied: protobuf in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from transformers[sentencepiece]<5.0.0,>=4.18.0->flair) (4.24.3)
Requirement already satisfied: MarkupSafe>=2.0 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from jinja2->torch==2.0.1) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in /home/mnaderi/.local/lib/python3.10/site-packages (from sympy->torch==2.0.1) (1.3.0)
Collecting pyarrow>=15.0.0 (from datasets<3.0.0,>=2.0.0->transformer-smaller-training-vocab>=0.2.3->flair)
  Downloading pyarrow-16.1.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Collecting pyarrow-hotfix (from datasets<3.0.0,>=2.0.0->transformer-smaller-training-vocab>=0.2.3->flair)
  Downloading pyarrow_hotfix-0.6-py3-none-any.whl.metadata (3.6 kB)
Collecting dill<0.3.9,>=0.3.0 (from datasets<3.0.0,>=2.0.0->transformer-smaller-training-vocab>=0.2.3->flair)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /home/mnaderi/.local/lib/python3.10/site-packages (from datasets<3.0.0,>=2.0.0->transformer-smaller-training-vocab>=0.2.3->flair) (2.2.1)
Collecting requests (from bpemb>=0.3.2->flair)
  Downloading requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting tqdm>=4.63.0 (from flair)
  Downloading tqdm-4.66.4-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.6/57.6 kB 1.7 MB/s eta 0:00:00[31m1.6 MB/s eta 0:00:01
Collecting xxhash (from datasets<3.0.0,>=2.0.0->transformer-smaller-training-vocab>=0.2.3->flair)
  Downloading xxhash-3.4.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess (from datasets<3.0.0,>=2.0.0->transformer-smaller-training-vocab>=0.2.3->flair)
  Downloading multiprocess-0.70.16-py310-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: aiohttp in /home/mnaderi/.local/lib/python3.10/site-packages (from datasets<3.0.0,>=2.0.0->transformer-smaller-training-vocab>=0.2.3->flair) (3.8.5)
Collecting huggingface-hub>=0.10.0 (from flair)
  Downloading huggingface_hub-0.23.4-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/mnaderi/.local/lib/python3.10/site-packages (from requests->bpemb>=0.3.2->flair) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from requests->bpemb>=0.3.2->flair) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from requests->bpemb>=0.3.2->flair) (2022.12.7)
Requirement already satisfied: accelerate>=0.20.3 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from transformers[torch]<5.0,>=4.1->transformer-smaller-training-vocab>=0.2.3->flair) (0.31.0)
Requirement already satisfied: soupsieve>1.2 in /home/mnaderi/.local/lib/python3.10/site-packages (from beautifulsoup4->gdown>=4.4.0->flair) (2.5)
INFO: pip is looking at multiple versions of requests[socks] to determine which version is compatible with other requirements. This could take a while.
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from requests[socks]->gdown>=4.4.0->flair) (1.7.1)
Requirement already satisfied: psutil in /home/mnaderi/.local/lib/python3.10/site-packages (from accelerate>=0.20.3->transformers[torch]<5.0,>=4.1->transformer-smaller-training-vocab>=0.2.3->flair) (5.9.5)
Requirement already satisfied: attrs>=17.3.0 in /home/mnaderi/.local/lib/python3.10/site-packages (from aiohttp->datasets<3.0.0,>=2.0.0->transformer-smaller-training-vocab>=0.2.3->flair) (23.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/mnaderi/.local/lib/python3.10/site-packages (from aiohttp->datasets<3.0.0,>=2.0.0->transformer-smaller-training-vocab>=0.2.3->flair) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /home/mnaderi/.local/lib/python3.10/site-packages (from aiohttp->datasets<3.0.0,>=2.0.0->transformer-smaller-training-vocab>=0.2.3->flair) (4.0.3)
Requirement already satisfied: yarl<2.0,>=1.0 in /home/mnaderi/.local/lib/python3.10/site-packages (from aiohttp->datasets<3.0.0,>=2.0.0->transformer-smaller-training-vocab>=0.2.3->flair) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /home/mnaderi/.local/lib/python3.10/site-packages (from aiohttp->datasets<3.0.0,>=2.0.0->transformer-smaller-training-vocab>=0.2.3->flair) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in /home/mnaderi/.local/lib/python3.10/site-packages (from aiohttp->datasets<3.0.0,>=2.0.0->transformer-smaller-training-vocab>=0.2.3->flair) (1.3.1)
Requirement already satisfied: pytz>=2020.1 in /home/mnaderi/miniconda3/lib/python3.10/site-packages (from pandas->datasets<3.0.0,>=2.0.0->transformer-smaller-training-vocab>=0.2.3->flair) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.7 in /home/mnaderi/.local/lib/python3.10/site-packages (from pandas->datasets<3.0.0,>=2.0.0->transformer-smaller-training-vocab>=0.2.3->flair) (2024.1)
Downloading torch-2.0.1-cp310-cp310-manylinux1_x86_64.whl (619.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 619.9/619.9 MB 8.3 MB/s eta 0:00:000m eta 0:00:01[36m0:00:01
Downloading triton-2.0.0-1-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (63.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.3/63.3 MB 16.3 MB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Downloading install-1.3.5-py3-none-any.whl (3.2 kB)
Downloading transformer_smaller_training_vocab-0.2.4-py3-none-any.whl (13 kB)
Downloading datasets-2.20.0-py3-none-any.whl (547 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 547.8/547.8 kB 19.5 MB/s eta 0:00:00
Downloading huggingface_hub-0.23.4-py3-none-any.whl (402 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 402.6/402.6 kB 21.4 MB/s eta 0:00:00
Downloading tqdm-4.66.4-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.3/78.3 kB 13.0 MB/s eta 0:00:00
Downloading requests-2.32.3-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 10.7 MB/s eta 0:00:00
Downloading sentencepiece-0.1.99-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 11.9 MB/s eta 0:00:00m eta 0:00:010:01
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 21.9 MB/s eta 0:00:00
Downloading pyarrow-16.1.0-cp310-cp310-manylinux_2_28_x86_64.whl (40.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.8/40.8 MB 15.5 MB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Downloading multiprocess-0.70.16-py310-none-any.whl (134 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 13.0 MB/s eta 0:00:00
Downloading pyarrow_hotfix-0.6-py3-none-any.whl (7.9 kB)
Downloading xxhash-3.4.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 21.5 MB/s eta 0:00:00
Installing collected packages: sentencepiece, xxhash, tqdm, requests, pyarrow-hotfix, pyarrow, install, dill, multiprocess, huggingface-hub, datasets, triton, torch, transformer-smaller-training-vocab
  Attempting uninstall: sentencepiece
    Found existing installation: sentencepiece 0.2.0

In [152]:
from flair.data import Sentence
from flair.models import SequenceTagger

# load tagger
tagger = SequenceTagger.load("flair/pos-english")

# make example sentence
sentence = Sentence(llm_al_str_doc)

# predict NER tags
tagger.predict(sentence)

# print sentence
print(sentence)

# print predicted NER spans
print('The following NER tags are found:')
# iterate over entities and print
for entity in sentence.get_spans('pos'):
    print(entity)

RuntimeError: Failed to import transformers.modeling_utils because of the following error (look up to see its traceback):
Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
No module named 'torch.distributed.checkpoint'

In [7]:
for ref, asr, llm in sequences:
    print_alignment(align3(ref, asr, llm))
    print()

        0      1    2     3
0   short         one  here
1    shoe  order  one  here
2  shorts         one   her

   0     1  2       3      4       5
0  I   eat     salami  pizza  salami
1  I  meat  a  salami  pizza  salami
2  I   eat  a     big  pizza

In [8]:
#sequences_1 = [
    # REF, ASR, LLM
    #("Ummm I go to school", "Um I go to school", "I go to school"),
#]

In [5]:
path = os.path.join(Root, "results/results-dev-set/results_noisy/results_tiny/results_sentence_confidence_tiny/results_GPT-3.5-Turbo_tiny/gpt-3.5-turbo-0125/results_without_sentence_confidence_tiny/corrected_transcriptions_sentence_confidence_tiny.json")

#path = "/home/mnaderi/Documents/thesis/chat-gpt-asr/results/results-dev-set/results_noisy/results_tiny/results_sentence_confidence_tiny/results_GPT-3.5-Turbo_tiny/gpt-3.5-turbo-0125/results_without_sentence_confidence_tiny/corrected_transcriptions_sentence_confidence_tiny.json"

with open(path, "r") as f:
    data = json.load(f)
    
    transcriptions = [RemovePunctuation()(d["asr_transcription"]["text"]).lower().strip() for d in data]
    reference_transcriptions = [RemovePunctuation()(d["reference_transcription"]).lower().strip() for d in data]
    corrected_transcriptions = [RemovePunctuation()(d["corrected_asr_transcription"]).lower().strip() for d in data]

In [14]:
# [[token.pos_ for token in nlp(tr)] for tr in corrected_transcriptions[:10]]
p, c = np.unique([token.pos_ for tr in corrected_transcriptions for token in nlp(tr)], return_counts=True)
df = pd.DataFrame([c], columns=p)
df

,ADJ,ADP,ADV,AUX,CCONJ,DET,INTJ,NOUN,NUM,PART,PRON,PROPN,PUNCT,SCONJ,SYM,VERB,X
0,3447,5733,3025,3560,2207,4889,225,9399,328,1463,7254,1244,5,1475,1,7296,4

In [15]:
df = df.drop(columns=["PUNCT","SYM","X"])
df

,ADJ,ADP,ADV,AUX,CCONJ,DET,INTJ,NOUN,NUM,PART,PRON,PROPN,SCONJ,VERB
0,3447,5733,3025,3560,2207,4889,225,9399,328,1463,7254,1244,1475,7296

In [29]:
# df.columns = [spacy.explain(_) for _ in df.columns]
(df / df.sum(axis=1).item()*100).round(2).T

                               0
adjective                   6.69
adposition                 11.12
adverb                      5.87
auxiliary                   6.91
coordinating conjunction    4.28
determiner                  9.48
interjection                0.44
noun                       18.23
numeral                     0.64
particle                    2.84
pronoun                    14.07
proper noun                 2.41
subordinating conjunction   2.86
verb                       14.15

In [48]:
import pandas as pd
from io import StringIO

latex_table = """
\\begin{table}[!h]
    \\centering
    \\caption{Language Model Performance by Part of Speech: Improved, IntroducedError LeftCorrect, and LeftIncorrect (\\%) in \\texttt{dev-other} dataset transcribed by the Tiny Whisper model. The summation across parts of speeches is 100.}
    \\label{tab:dev_other_pos_1}
      \\resizebox{\\textwidth}{!}{%
    \\begin{tabular}{lrrrrr}
\\toprule
 & Improved & IntroducedError & LeftCorrect & LeftIncorrect & Percentage \\\\
\\midrule
adjective & 7.81 & 7.57 & 6.65 & 6.61 &6.69 \\\\
adposition & 10.91 & 11.89 & 11.58 & 8.30 & 11.12 \\\\
adverb & 5.72 & 3.51 & 6.07 & 4.75 &5.87 \\\\
auxiliary & 3.30 & 4.86 & 7.23 & 5.77 & 6.91 \\\\
coordinating conjunction & 3.10 & 2.70 & 4.39 & 3.96&4.28 \\\\
determiner & 5.59 & 7.57 & 9.86 & 8.11& 9.48\\\\
interjection & 0.13 & 0.00 & 0.40 & 0.73&0.44 \\\\
noun & 27.14 & 22.16 & 17.01 & 23.72 &18.23\\\\
numeral & 1.14 & 1.08 & 0.53 & 1.14 &0.64\\\\
particle & 2.42 & 1.89 & 3.02 & 1.82 &2.84\\\\
pronoun & 6.60 & 11.08 & 14.96 & 10.32 &14.07\\\\
proper noun & 4.85 & 2.16 & 1.51 & 7.51&2.41 \\\\
subordinating conjunction & 2.15 & 3.51 & 3.03 & 1.94& 2.86 \\\\
verb & 19.12 & 20.00 & 13.74 & 15.34& 14.15\\\\
\\bottomrule
\\end{tabular}
}
\\end{table}
"""

# Extract the data part from the latex table
data_str = latex_table.split('\\begin{tabular}')[1].split('\\end{tabular}')[0]
data_str = data_str.split('\\midrule')[1].split('\\bottomrule')[0].strip()

# Convert the data string into a CSV format
data_str = data_str.replace('\\\\', '\n').replace('&', ',').replace(' ', '')

# Create a DataFrame from the CSV string
data = StringIO(data_str)
df = pd.read_csv(data, sep=',', names=["Part of Speech", "Improved", "IntroducedError", "LeftCorrect", "LeftIncorrect", "Percentage"])
df = df.set_index("Part of Speech")
df

,Improved,IntroducedError,LeftCorrect,LeftIncorrect,Percentage
Part of Speech,,,,,
adjective,7.81,7.57,6.65,6.61,6.69
adposition,10.91,11.89,11.58,8.30,11.12
adverb,5.72,3.51,6.07,4.75,5.87
auxiliary,3.30,4.86,7.23,5.77,6.91
coordinatingconjunction,3.10,2.70,4.39,3.96,4.28
determiner,5.59,7.57,9.86,8.11,9.48
interjection,0.13,0.00,0.40,0.73,0.44
noun,27.14,22.16,17.01,23.72,18.23
numeral,1.14,1.08,0.53,1.14,0.64
particle,2.42,1.89,3.02,1.82,2.84
pronoun,6.60,11.08,14.96,10.32,14.07
propernoun,4.85,2.16,1.51,7.51,2.41
subordinatingconjunction,2.15,3.51,3.03,1.94,2.86
verb,19.12,20.00,13.74,15.34,14.15

In [50]:
df_new = df.div(df['Percentage'], axis=0).round(2)
df_new

,Improved,IntroducedError,LeftCorrect,LeftIncorrect,Percentage
Part of Speech,,,,,
adjective,1.17,1.13,0.99,0.99,1.0
adposition,0.98,1.07,1.04,0.75,1.0
adverb,0.97,0.60,1.03,0.81,1.0
auxiliary,0.48,0.70,1.05,0.84,1.0
coordinatingconjunction,0.72,0.63,1.03,0.93,1.0
determiner,0.59,0.80,1.04,0.86,1.0
interjection,0.30,0.00,0.91,1.66,1.0
noun,1.49,1.22,0.93,1.30,1.0
numeral,1.78,1.69,0.83,1.78,1.0
particle,0.85,0.67,1.06,0.64,1.0
pronoun,0.47,0.79,1.06,0.73,1.0
propernoun,2.01,0.90,0.63,3.12,1.0
subordinatingconjunction,0.75,1.23,1.06,0.68,1.0
verb,1.35,1.41,0.97,1.08,1.0

In [51]:
df_desired = df.astype(str) + " (" + df_new.astype(str) + ")"
df_desired

,Improved,IntroducedError,LeftCorrect,LeftIncorrect,Percentage
Part of Speech,,,,,
adjective,7.81 (1.17),7.57 (1.13),6.65 (0.99),6.61 (0.99),6.69 (1.0)
adposition,10.91 (0.98),11.89 (1.07),11.58 (1.04),8.3 (0.75),11.12 (1.0)
adverb,5.72 (0.97),3.51 (0.6),6.07 (1.03),4.75 (0.81),5.87 (1.0)
auxiliary,3.3 (0.48),4.86 (0.7),7.23 (1.05),5.77 (0.84),6.91 (1.0)
coordinatingconjunction,3.1 (0.72),2.7 (0.63),4.39 (1.03),3.96 (0.93),4.28 (1.0)
determiner,5.59 (0.59),7.57 (0.8),9.86 (1.04),8.11 (0.86),9.48 (1.0)
interjection,0.13 (0.3),0.0 (0.0),0.4 (0.91),0.73 (1.66),0.44 (1.0)
noun,27.14 (1.49),22.16 (1.22),17.01 (0.93),23.72 (1.3),18.23 (1.0)
numeral,1.14 (1.78),1.08 (1.69),0.53 (0.83),1.14 (1.78),0.64 (1.0)
particle,2.42 (0.85),1.89 (0.67),3.02 (1.06),1.82 (0.64),2.84 (1.0)
pronoun,6.6 (0.47),11.08 (0.79),14.96 (1.06),10.32 (0.73),14.07 (1.0)
propernoun,4.85 (2.01),2.16 (0.9),1.51 (0.63),7.51 (3.12),2.41 (1.0)
subordinatingconjunction,2.15 (0.75),3.51 (1.23),3.03 (1.06),1.94 (0.68),2.86 (1.0)
verb,19.12 (1.35),20.0 (1.41),13.74 (0.97),15.34 (1.08),14.15 (1.0)

In [53]:
print(df_desired.to_latex())

\begin{tabular}{llllll}
\toprule
 & Improved & IntroducedError & LeftCorrect & LeftIncorrect & Percentage \\
Part of Speech &  &  &  &  &  \\
\midrule
adjective & 7.81 (1.17) & 7.57 (1.13) & 6.65 (0.99) & 6.61 (0.99) & 6.69 (1.0) \\
adposition & 10.91 (0.98) & 11.89 (1.07) & 11.58 (1.04) & 8.3 (0.75) & 11.12 (1.0) \\
adverb & 5.72 (0.97) & 3.51 (0.6) & 6.07 (1.03) & 4.75 (0.81) & 5.87 (1.0) \\
auxiliary & 3.3 (0.48) & 4.86 (0.7) & 7.23 (1.05) & 5.77 (0.84) & 6.91 (1.0) \\
coordinatingconjunction & 3.1 (0.72) & 2.7 (0.63) & 4.39 (1.03) & 3.96 (0.93) & 4.28 (1.0) \\
determiner & 5.59 (0.59) & 7.57 (0.8) & 9.86 (1.04) & 8.11 (0.86) & 9.48 (1.0) \\
interjection & 0.13 (0.3) & 0.0 (0.0) & 0.4 (0.91) & 0.73 (1.66) & 0.44 (1.0) \\
noun & 27.14 (1.49) & 22.16 (1.22) & 17.01 (0.93) & 23.72 (1.3) & 18.23 (1.0) \\
numeral & 1.14 (1.78) & 1.08 (1.69) & 0.53 (0.83) & 1.14 (1.78) & 0.64 (1.0) \\
particle & 2.42 (0.85) & 1.89 (0.67) & 3.02 (1.06) & 1.82 (0.64) & 2.84 (1.0) \\
pronoun & 6.6 (0.47) & 11.08 (0.79) & 14.96 (1.06) & 10.32 (0.73) & 14.07 (1.0) \\
propernoun & 4.85 (2.01) & 2.16 (0.9) & 1.51 (0.63) & 7.51 (3.12) & 2.41 (1.0) \\
subordinatingconjunction & 2.15 (0.75) & 3.51 (1.23) & 3.03 (1.06) & 1.94 (0.68) & 2.86 (1.0) \\
verb & 19.12 (1.35) & 20.0 (1.41) & 13.74 (0.97) & 15.34 (1.08) & 14.15 (1.0) \\
\bottomrule
\end{tabular}

In [10]:
for i, (ref, asr, llm) in enumerate(zip(reference_transcriptions, transcriptions, corrected_transcriptions)):
    if i > 2000 and i<2010:
        print_alignment(align3(ref, asr, llm))
        print()

    0        1   2       3    4       5   6    7     8         9   ...    37  \
0  one  morning  as   kanti  was  seated  in  his  boat  cleaning  ...  edge
1  one  morning  as  gandhi  was  seated  in  his  boat  cleaning  ...  edge
2  one  morning  as  gandhi  was  seated  in  his  boat  cleaning  ...  edge

     38   39     40    41         42       43  44   45       46
0  with  two  white        ducklings  clasped  to  her   breast
1  with  two  white  tuck      links  clasped  to  her  pressed
2  with  two  white        ducklings  clasped  to  her   breast

[3 rows x 47 columns]

    0     1    2    3      4     5    6      7    8        9     10         11
0  the  girl  put  the  birds  into  the  water  and  watched  them  anxiously
1  the  girl  put  the  birds  into  the  water  and    watch  them  anxiously
2  the  girl  put  the  birds  into  the  water  and  watched  them  anxiously

        0      1      2      3    4    5   6    7     8         9    10  \
0  looking  round  kanti         saw  one  of  his   men  pointing   an
1  looking  round   cant  these  are  one  of  his  main  pointing  and
2  looking  round   cant  these  are  one  of  his   men  pointing  and

         11   12  13   14     15
0  unloaded  gun  at  the  ducks
1  unloaded  gun  at  the  rocks
2  unloaded  gun  at  the  rocks

      0      1    2      3    4      5    6        7       8    9   ...  38  \
0  after  kanti  had  eaten  and  drunk  the  brahmin  begged  him  ...  be
1  after  kanti  had  eaten  and  drunk  the  brahmin  pegged  him  ...  be
2  after  kanti  had  eaten  and  drunk  the  brahmin  begged  him  ...  be

   39   40       41   42 43     44    45      46         47
0  of  any  service  sir  i  shall  deem  myself  fortunate
1  of  any  service       i  shall  keep  myself  fortunate
2  of  any  service       i  shall  deem  myself  fortunate

[3 rows x 48 columns]

       0     1   2         3    4    5
0  kanti  went  on  cleaning  his  gun
1  kanti  went  on  cleaning  his  gun
2  kanti  went  on  cleaning  his  gun

    0      1   2    3      4       5   6     7    8    9         10  11  \
0  the  light  of  the  lamps  seemed  to  grow  dim  and  darkness  to
1  the  light  of  the   lamp  seemed  to  grow  dim  and  darkness  to
2  the  light  of  the   lamp  seemed  to  grow  dim  and  darkness  to

        12   13    14  15   16     17       18
0  tarnish  the  face  of  the  bride  herself
1  tarnish  the  face  of  the  pride  herself
2  tarnish  the  face  of  the  bride  herself

    0       1      2         3    4       5    6     7     8
0  so  saying  kanti  repeated  his  salute  and  went  back
1  so  seeing  conti  repeated  his  salute  and  went  back
2  so  seeing  conti  repeated  his  salute  and  went  back

   0    1     2    3      4           5        6   7    8         9   ...  \
0  in  due  time  the         bridegroom  arrived  on  his  elephant  ...
1  in  due  time  the  pride       groom  arrived  on  his  elephant  ...
2  in  due  time  the         bridegroom  arrived  on  his  elephant  ...

    14    15 16          17    18          19   20   21        22     23
0  and  with  a  torchlight        procession  and  the  ceremony  began
1  and  with  a    thoughts  like  procession   in  the  ceremony  began
2  and  with  a   grandlike        procession       the  ceremony  began

[3 rows x 24 columns]

   0      1   2     3      4     5    6            7    8    9   ...   13  \
0  at  first  he  felt  angry  with  his       father   in  law  ...  had
1  at  first  he  felt  angry  with  his       father  and  law  ...  had
2  at  first  he  felt  angry  with  his  fatherinlaw            ...  had

      14   15   16    17   18       19   20  21       22
0  shown  him  one  girl  and  married  him  to  another
1  shown  him  one  girl  and  married  him  to  another
2  shown  him  one  girl  and  married  him  to  another

[3 rows x 23 columns]

In [125]:
def identify_operation(r, a, l):
    if r == a == l:
        return "-"
    elif a != "" and l == "":
        return "D"
    elif a == "" and l != "":
        return "I"
    elif a != "" and l != "" and a != l:
        return "S"
    else:
        raise Exception('can not be the case!', r, a, l)

def identify_edit_type(ref, asr, llm, tokenizer_fn=None):
    edit_types = []
    operations = []
    edits = {"Improved":[],"IntroducedError":[],"LeftCorrect":[],"LeftIncorrect":[]}
    rr, aa, ll = align3(ref, asr, llm, tokenizer_fn)
    if len(rr) == len(aa) == len(ll):
        for r,a,l in zip(rr,aa,ll):
            operation = identify_operation(r, a, l)
            operations.append(operation)
            if a == l == r:
                edit_types.append("LeftCorrect")  # left it correct
                edits["LeftCorrect"].append((a,l,r))
            elif a != l and l == r:
                edit_types.append("Improved")  # improve it
                edits["Improved"].append((a,l,r))
            elif a != r and l != r:
                edit_types.append("LeftIncorrect")  # left it incorrect
                edits["LeftIncorrect"].append((a,l,r))
            elif a == r and l != r:
                edit_types.append("IntroducedError")  # introducing an error
                edits["IntroducedError"].append((a,l,r))
    else:
        raise Exception
    return edit_types, edits, operations

In [12]:
tokenizer_fn = lambda s: [token.text for token in nlp(s)]
data_1 = []
data_2 = []
for i, (ref, asr, llm) in enumerate(zip(reference_transcriptions, transcriptions, corrected_transcriptions)):
    #if i > 10:
        #break
    edit_types, edits = identify_edit_type(ref, asr, llm, tokenizer_fn)
    word_counts = {'Improved': 0, 'IntroducedError': 0, 'LeftCorrect': 0, 'LeftIncorrect': 0}
    poses = [token.pos_ for token in nlp(llm)]
    data_2.append(list(zip(edit_types, poses)))
    for edit_type in edit_types:
        word_counts[edit_type] += 1
        
    
    # Create a DataFrame to store word counts by edit type
    data_1.append(word_counts)
    # df_edit_types = pd.DataFrame(word_counts.items(), columns=['Type', 'Count'])
    
    # Display the DataFrame
    # print("asr: {} len:{} \nllm: {} len: {} \nref: {} len: {}".format(asr, len(asr), llm, len(llm), ref, len(ref)))
    # print('edits: ', edits)
    # print(i, df_edit_types , "\n")

In [13]:
pd.DataFrame(data_1)

      Improved  IntroducedError  LeftCorrect  LeftIncorrect
0            1                0           21              0
1            1                0            9              0
2            0                0           13              0
3            2                0           25              0
4            0                0           10              1
...        ...              ...          ...            ...
2859         0                0           13              2
2860         0                0           11              0
2861         0                0           20              2
2862         1                0           30              1
2863         0                0            8              0

[2864 rows x 4 columns]

In [14]:
import pandas as pd

# Flatten the list of lists
flattened_data = [item for sublist in data_2 for item in sublist]

# Initialize a dictionary to store counts
combination_counts = {}

# Count the occurrences of each unique combination
for operation, pos in flattened_data:
    if (operation, pos) in combination_counts:
        combination_counts[(operation, pos)] += 1
    else:
        combination_counts[(operation, pos)] = 1

# Convert the dictionary into a DataFrame
df = pd.DataFrame(combination_counts.items(), columns=['Combination', 'Count'])

# # Split the 'Combination' column into 'Operation' and 'POS'
df[['Operation', 'POS']] = pd.DataFrame(df['Combination'].tolist(), index=df.index)

# Drop the 'Combination' column
df.drop(columns=['Combination'], inplace=True)

# Pivot the DataFrame to have operations as rows and POS counts as columns
pivot_df = df.pivot_table(index='Operation', columns='POS', values='Count', fill_value=0)

pivot_df.to_csv('final_pos_result.csv')

pivot_df
# # Display the resulting DataFrame
# print(pivot_df)

POS,ADJ,ADP,ADV,AUX,CCONJ,DET,INTJ,NOUN,NUM,PART,PRON,PROPN,PUNCT,SCONJ,SYM,VERB,X
Operation,,,,,,,,,,,,,,,,,
Improved,116.0,162.0,85.0,49.0,46.0,83.0,2.0,403.0,17.0,36.0,98.0,72.0,0.0,32.0,0.0,284.0,0.0
IntroducedError,28.0,44.0,13.0,18.0,10.0,28.0,0.0,82.0,4.0,7.0,41.0,8.0,0.0,13.0,0.0,74.0,0.0
LeftCorrect,2849.0,4957.0,2601.0,3097.0,1879.0,4221.0,173.0,7285.0,229.0,1295.0,6406.0,648.0,5.0,1297.0,0.0,5884.0,3.0
LeftIncorrect,454.0,570.0,326.0,396.0,272.0,557.0,50.0,1629.0,78.0,125.0,709.0,516.0,0.0,133.0,1.0,1054.0,1.0

In [ ]:
# axis=0 # sum of rows
axis=1 # sum of columns
(pivot_df/pivot_df.sum(axis)*100).round(2)

## debug

In [44]:
data = {
    'Improved': [116.0, 162.0, 85.0, 49.0, 46.0, 83.0, 2.0, 403.0, 17.0, 36.0, 98.0, 72.0, 0.0, 32.0, 0.0, 284.0, 0.0],
    'IntroducedError': [28.0, 44.0, 13.0, 18.0, 10.0, 28.0, 0.0, 82.0, 4.0, 7.0, 41.0, 8.0, 0.0, 13.0, 0.0, 74.0, 0.0],
    'LeftCorrect': [2849.0, 4957.0, 2601.0, 3097.0, 1879.0, 4221.0, 173.0, 7285.0, 229.0, 1295.0, 6406.0, 648.0, 5.0, 1297.0, 0.0, 5884.0, 3.0],
    'LeftIncorrect': [454.0, 570.0, 326.0, 396.0, 272.0, 557.0, 50.0, 1629.0, 78.0, 125.0, 709.0, 516.0, 0.0, 133.0, 1.0, 1054.0, 1.0]
}
df = pd.DataFrame(data, index=['ADJ', 'ADP', 'ADV', 'AUX', 'CCONJ', 'DET', 'INTJ', 'NOUN', 'NUM', 'PART', 'PRON', 'PROPN', 'PUNCT', 'SCONJ', 'SYM', 'VERB', 'X'])
df = df.T
df

,ADJ,ADP,ADV,AUX,CCONJ,DET,INTJ,NOUN,NUM,PART,PRON,PROPN,PUNCT,SCONJ,SYM,VERB,X
Improved,116.0,162.0,85.0,49.0,46.0,83.0,2.0,403.0,17.0,36.0,98.0,72.0,0.0,32.0,0.0,284.0,0.0
IntroducedError,28.0,44.0,13.0,18.0,10.0,28.0,0.0,82.0,4.0,7.0,41.0,8.0,0.0,13.0,0.0,74.0,0.0
LeftCorrect,2849.0,4957.0,2601.0,3097.0,1879.0,4221.0,173.0,7285.0,229.0,1295.0,6406.0,648.0,5.0,1297.0,0.0,5884.0,3.0
LeftIncorrect,454.0,570.0,326.0,396.0,272.0,557.0,50.0,1629.0,78.0,125.0,709.0,516.0,0.0,133.0,1.0,1054.0,1.0

In [51]:
df = df.drop(columns=["X", "SYM", "PUNCT"])

In [62]:
df_column_wise = (df.div(df.sum(axis=1), axis=0)*100).round(2)
df_column_wise
# print(df_column_wise.T.to_latex(float_format="{:.2f}".format))

,ADJ,ADP,ADV,AUX,CCONJ,DET,INTJ,NOUN,NUM,PART,PRON,PROPN,SCONJ,VERB
Improved,7.81,10.91,5.72,3.30,3.10,5.59,0.13,27.14,1.14,2.42,6.60,4.85,2.15,19.12
IntroducedError,7.57,11.89,3.51,4.86,2.70,7.57,0.00,22.16,1.08,1.89,11.08,2.16,3.51,20.00
LeftCorrect,6.65,11.58,6.07,7.23,4.39,9.86,0.40,17.01,0.53,3.02,14.96,1.51,3.03,13.74
LeftIncorrect,6.61,8.30,4.75,5.77,3.96,8.11,0.73,23.72,1.14,1.82,10.32,7.51,1.94,15.34

In [61]:
df_row_wise = (df.div(df.sum(axis=0), axis=1)*100).round(2)
df_row_wise.T
# print(df_row_wise.T.to_latex(float_format="{:.2f}".format))

       Improved  IntroducedError  LeftCorrect  LeftIncorrect
ADJ        3.37             0.81        82.65          13.17
ADP        2.83             0.77        86.46           9.94
ADV        2.81             0.43        85.98          10.78
AUX        1.38             0.51        86.99          11.12
CCONJ      2.08             0.45        85.14          12.32
DET        1.70             0.57        86.34          11.39
INTJ       0.89             0.00        76.89          22.22
NOUN       4.29             0.87        77.51          17.33
NUM        5.18             1.22        69.82          23.78
PART       2.46             0.48        88.52           8.54
PRON       1.35             0.57        88.31           9.77
PROPN      5.79             0.64        52.09          41.48
SCONJ      2.17             0.88        87.93           9.02
VERB       3.89             1.01        80.65          14.45

In [17]:
ref = "i don't go to school"
asr = "i not go to school"
ll  = "i don't go to uni all"
align3(ref, asr, ll, tokenizer_fn )

(['i', 'do', "n't", 'go', 'to', '', 'school'],
 ['i', '', 'not', 'go', 'to', '', 'school'],
 ['i', 'do', "n't", 'go', 'to', 'uni', 'all'])

In [1]:
import pandas as pd

In [5]:
df = pd.DataFrame({"A":[1,2,3],"B": [4,5,6]}, index=['a','b','c'])
df

   A  B
a  1  4
b  2  5
c  3  6

In [7]:
sum_of_rows = df.sum(0)
(df/sum_of_rows*100).round(2)

       A      B
a  16.67  26.67
b  33.33  33.33
c  50.00  40.00

## debug Parts of speech

In [11]:
def identify_operation(a, l):
    if a != "" and l == "":
        return "D"
    elif a == "" and l != "":
        return "I"
    elif a != "" and l != "" and a != l:
        return "S"
    else:
        return '-'

def identify_edit_type(ref, asr, llm, tokenizer_fn=None):
    edit_types = []
    operations = []
    edits = {"Improved":[],"IntroducedError":[],"LeftCorrect":[],"LeftIncorrect":[]}
    rr, aa, ll = align3(ref, asr, llm, tokenizer_fn)
    if len(rr) == len(aa) == len(ll):
        for r,a,l in zip(rr,aa,ll):
            operation = identify_operation(a, l)
            operations.append(operation)
            if a == l == r:
                edit_types.append("LeftCorrect")  # left it correct
                edits["LeftCorrect"].append((a,l,r))
            elif a != l and l == r:
                edit_types.append("Improved")  # improve it
                edits["Improved"].append((a,l,r))
            elif a != r and l != r:
                edit_types.append("LeftIncorrect")  # left it incorrect
                edits["LeftIncorrect"].append((a,l,r))
            elif a == r and l != r:
                edit_types.append("IntroducedError")  # introducing an error
                edits["IntroducedError"].append((a,l,r))
    else:
        raise Exception
    return edit_types, edits, operations

In [21]:
from tqdm import tqdm

tokenizer_fn = lambda s: [token.text for token in nlp(s)]

d = {}
for asr, ref, llm in tqdm(zip(transcriptions,reference_transcriptions,corrected_transcriptions), 
                         total=len(transcriptions)):
    
    edit_types, edits, operations = identify_edit_type(ref, asr, llm, tokenizer_fn=tokenizer_fn)
    
    # list of tokens of aligned ref, asr, and llm 
    ref_aligned, asr_aligned, llm_aligned = align3(ref,asr,llm, tokenizer_fn=tokenizer_fn)
    llm_aligned_str = " ".join([r if r else "*" for r in llm_aligned])
    asr_aligned_str = " ".join([r if r else "*" for r in asr_aligned])
    ref_aligned_str = " ".join([r if r else "*" for r in ref_aligned])
    
    # string of aligned ref, asr, and llm with '' replaced by *
    llm_doc = nlp(llm_aligned_str)
    ref_doc = nlp(ref_aligned_str)
    asr_doc = nlp(asr_aligned_str)
    assert len(llm_doc) == len(asr_doc) == len(ref_doc)
    
    for i in range(len(asr_doc)):

        operation = operations[i]
        edit_type = edit_types[i]
        a_token = asr_doc[i]
        a_pos = "MASKED" if a_token.text == "*" else a_token.pos_
        
        l_token = llm_doc[i]
        l_pos = "MASKED" if l_token.text == "*" else l_token.pos_

        # identify pos
        if operation == 'I':
            pos = l_pos
        elif operation == 'D':
            pos = a_pos
        elif operation == '-':
            pos = a_pos
        elif operation == 'S':
            pos = a_pos
    
        d[(edit_type, pos)] = d.get((edit_type, pos), 0) + 1
        # print(f"{operation=}, {edit_type=}, {a_pos=} {l_pos=}, {pos=}")

d

 11%|████████▋                                                                     | 321/2864 [32:10<4:14:51,  6.01s/it]

KeyboardInterrupt:

In [ ]:
keys, values = zip(*d.items())
ops, poses = zip(*keys)

df = pd.DataFrame(0, columns=np.unique(ops), index=np.unique(poses))
for (op,pos), value in d.items():
    df.loc[pos, op] += value

df